### ISSUE TITLE
Bug with the Calefactor

### ISSUE THREAD

**Issue by Superdarklink** [Mithion/ArsMagica2#1023]
I was messing around with the calefactor trying to figure out how it worked. I placed a fish inside to be cooked and thought i had to use runes to cook. It didn't work, so i exited the UI and looked it up on the wiki. When i returned to the game i couldn't enter the UI. At all. So i tried to break it with my pick, prompting the game to freeze for a few seconds and ultimately crash.

1.7.10

Forge: 10.13.1.1224

AM2:1.4.0.005

**Comment by Mithion** [comment]
Log files or it didn't happen.

**Comment by Superdarklink** [comment]
Site doesnt allow Word docs. so here.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 1/27/15 9:45 PM
Description: Rendering Block Entity

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:212)
	at net.minecraft.client.renderer.entity.RenderItem.renderDroppedItem(RenderItem.java:383)
	at net.minecraft.client.renderer.entity.RenderItem.func_77020_a(RenderItem.java:239)
	at net.minecraft.client.renderer.entity.RenderItem.func_76986_a(RenderItem.java:211)
	at am2.blocks.renderers.CalefactorRenderer.RenderItemAtCoords(CalefactorRenderer.java:119)
	at am2.blocks.renderers.CalefactorRenderer.renderAModelAt(CalefactorRenderer.java:111)
	at am2.blocks.renderers.CalefactorRenderer.func_147500_a(CalefactorRenderer.java:124)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at am2.blocks.renderers.TechneBlockRenderHandler.renderWorldBlock(TechneBlockRenderHandler.java:90)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.RenderBlocks.func_147792_a(RenderBlocks.java:228)
	at net.minecraft.client.renderer.RenderGlobal.drawBlockDamageTexture(RenderGlobal.java:1652)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1264)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:212)
	at net.minecraft.client.renderer.entity.RenderItem.renderDroppedItem(RenderItem.java:383)
	at net.minecraft.client.renderer.entity.RenderItem.func_77020_a(RenderItem.java:239)
	at net.minecraft.client.renderer.entity.RenderItem.func_76986_a(RenderItem.java:211)
	at am2.blocks.renderers.CalefactorRenderer.RenderItemAtCoords(CalefactorRenderer.java:119)
	at am2.blocks.renderers.CalefactorRenderer.renderAModelAt(CalefactorRenderer.java:111)
	at am2.blocks.renderers.CalefactorRenderer.func_147500_a(CalefactorRenderer.java:124)

-- Block Entity Details --
Details:
	Name: TileEntityCalefactor // am2.blocks.tileentities.TileEntityCalefactor
	Block type: ID #189 (tile.arsmagica2:calefactor // am2.blocks.BlockCalefactor)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-328,92,321), Chunk: (at 8,5,1 in -21,20; contains blocks -336,0,320 to -321,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #189 (tile.arsmagica2:calefactor // am2.blocks.BlockCalefactor)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at am2.blocks.renderers.TechneBlockRenderHandler.renderWorldBlock(TechneBlockRenderHandler.java:90)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.RenderBlocks.func_147792_a(RenderBlocks.java:228)
	at net.minecraft.client.renderer.RenderGlobal.drawBlockDamageTexture(RenderGlobal.java:1652)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1264)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['superdarklink'/352, l='MpServer', x=-327.53, y=93.62, z=319.40]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-228,64,244), Chunk: (at 12,4,4 in -15,15; contains blocks -240,0,240 to -225,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 436026 game time, 531002 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntitySquid['Squid'/143, l='MpServer', x=-298.28, y=61.38, z=303.38], EntitySquid['Squid'/131, l='MpServer', x=-305.50, y=60.00, z=304.50], EntityTameableDragon['Nether Dragon'/130, l='MpServer', x=-314.25, y=92.13, z=294.00], EntitySquid['Squid'/133, l='MpServer', x=-308.16, y=59.00, z=313.50], EntitySquid['Squid'/132, l='MpServer', x=-314.88, y=60.38, z=306.50], EntitySquid['Squid'/134, l='MpServer', x=-309.28, y=60.03, z=310.50], EntitySquid['Squid'/144, l='MpServer', x=-300.13, y=60.00, z=315.63], EntityPainting['Painting'/145, l='MpServer', x=-304.00, y=94.00, z=312.94], EntitySquid['Squid'/146, l='MpServer', x=-298.88, y=60.31, z=316.47], EntitySquid['Squid'/147, l='MpServer', x=-300.41, y=60.38, z=325.31], EntitySkeleton['Skeleton'/148, l='MpServer', x=-294.47, y=19.00, z=352.66], EntityRumia['Rumia'/149, l='MpServer', x=-294.97, y=37.19, z=397.50], EntityRumia['Rumia'/150, l='MpServer', x=-293.50, y=37.20, z=397.50], EntityPig['Pig'/168, l='MpServer', x=-285.03, y=63.00, z=396.03], EntityPainting['Painting'/145, l='MpServer', x=-304.00, y=94.00, z=312.94], EntityTHFairy['Fairy'/167, l='MpServer', x=-288.25, y=65.19, z=262.91], EntityTHFairy['Fairy'/166, l='MpServer', x=-291.25, y=66.41, z=256.28], EntityTHPhantom['Phantom'/104, l='MpServer', x=-394.50, y=68.00, z=369.50], EntityCow['Cow'/119, l='MpServer', x=-349.38, y=63.00, z=305.75], EntityClientPlayerMP['superdarklink'/352, l='MpServer', x=-327.53, y=93.62, z=319.40], EntitySquid['Squid'/116, l='MpServer', x=-356.06, y=50.00, z=297.50], EntityPig['Pig'/114, l='MpServer', x=-372.41, y=63.00, z=376.19], EntityCow['Cow'/113, l='MpServer', x=-379.28, y=68.00, z=309.72], EntityTHFairy['Fairy'/112, l='MpServer', x=-368.69, y=69.50, z=262.31], EntityTHPhantom['Phantom'/182, l='MpServer', x=-254.69, y=53.00, z=287.69], EntityTHPhantom['Phantom'/183, l='MpServer', x=-251.50, y=53.00, z=284.50], EntityTHPhantom['Phantom'/181, l='MpServer', x=-254.50, y=53.00, z=283.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 192812744 bytes (183 MB) / 423014400 bytes (403 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1224 Minecraft Forge 10.13.1.1224 14 mods loaded, 14 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1224} [Forge Mod Loader] (forge-1.7.10-10.13.1.1224.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.1.1224} [Minecraft Forge] (forge-1.7.10-10.13.1.1224.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.3.26} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.56} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.56-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SomniaCore{1.3.0.15} [SomniaCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.005} [Ars Magica 2] (1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DragonMounts{r39} [Dragon Mounts] (Dragon-Mounts-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_Kenshiro{1.2.1} [Kenshiro Mod] (KenshiroMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.0.00} [Mystcraft] (Mystcraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Somnia{-au} [Somnia] (Somnia-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	THKaguyaMod{2.76_1.7.10} [Itutu no Nandai MOD+] (Touhou-Items-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.1.1224
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD6370D Graphics   GL version 4.1.10834 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Mithion** [comment]
Version 006 fixed that issue. Try upgrading.
