### ISSUE TITLE
Ticking entity null pointer exception

### ISSUE THREAD

**Issue by DLemberg** [Mithion/ArsMagica2#1030]
I'm seeing periodic crashes on a 1.7.10 server with Forge 1286 and Java 1.8 due to an Ars Magica 2 Dark Mage.  Error message is always the same - a null pointer exception from a ticking entity, and the entity is always a Dark Mage.  I've been working around it by restarting the server in peaceful mode, then bringing it down and bringing it back up in normal.  Log is below.  I've got a snapshot of the world, mods, and configs with the error so that it crashes on startup if it is helpful, but the snapshot is 90 megs compressed.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/6/15 8:19 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18)
	at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18)
	at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: arsmagica2.MobDarkMage (am2.entities.EntityDarkMage)
	Entity ID: 84
	Entity Name: Dark Mage
	Entity's Exact location: -84.50, 67.00, 960.23
	Entity's Block location: World: (-85,67,960), Chunk: (at 11,4,0 in -6,60; contains blocks -96,0,960 to -81,255,975), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['danlemberg'/165, l='world', x=-164.86, y=78.00, z=973.40]]
	Chunk stats: ServerChunkCache: 999 Drop: 0
	Level seed: 5089460919707135225
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (44,64,1020), Chunk: (at 12,4,12 in 2,63; contains blocks 32,0,1008 to 47,255,1023), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 1415024 game time, 1415024 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 23992 (now: false), thunder time: 93657 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 293894064 bytes (280 MB) / 806354944 bytes (769 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 37 mods loaded, 37 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1286} [Forge Mod Loader] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1286} [Minecraft Forge] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.005} [Ars Magica 2] (AM2-1.4.0.006.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfare{2.4.83-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareAutomation{2.4.83-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareNEIPlugin{2.4.83-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareNpc{2.4.83-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareStructure{2.4.83-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareVehicle{2.4.83-beta-MC1.7.10} [Ancient Warfare Vehicles] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppleCore{1.0.2} [AppleCore] (AppleCore-mc1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1057-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.3.0a} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0a-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chocolateQuest{0.0} [Chocolate Quest] (chocolateQuest-1.7.10-BETA2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	props{1.11} [Decocraft] (Decocraft-v1.11_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IguanaTweaks{1.7.10-Beta-19} [Iguana Tweaks] (IguanaTweaks-1.7.10-Beta-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_FairPlay_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mca{4.1.5} [Minecraft Comes Alive] (MCA-1.7.10-4.1.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	supercraftingframe{1.7.10.2} [Super Crafting Frame] (supercraftingframe-1.7.10.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)] (VillageInfoSSP-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WailaHarvestability{1.1.1} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['danlemberg'/165, l='world', x=-164.86, y=78.00, z=973.40]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DLemberg** [comment]
Hmmm, just noticed another odd thing.  I'm using Ars Magica 2 1.4.0.006, but the above log says 1.4.0.005.  Maybe a variable wasn't updated when the latest build was created?
