### ISSUE TITLE
AM2 spams log file with NullPointerException

### ISSUE THREAD

**Issue by twothe** [Mithion/ArsMagica2#1073]
At magic level 1 with full mana the log file is constantly spammed with the following exception:

    java.lang.NullPointerException
      at am2.playerextensions.ExtendedProperties.getMaxMana(ExtendedProperties.java:253)
      at am2.playerextensions.ExtendedProperties.setMagicLevelWithMana(ExtendedProperties.java:428)
      at am2.playerextensions.ExtendedProperties.loadNBTData(ExtendedProperties.java:835)
      at net.minecraft.entity.Entity.func_70020_e(Entity.java:1419)
      at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98265_a(SourceFile:117)
      at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98281_h(SourceFile:236)
      at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147517_a(SourceFile:20)
      at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:15)
      at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:10)
      at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
      at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
      at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
      at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
      at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
      at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
      at net.minecraft.client.main.Main.main(SourceFile:148)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:483)
      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Mithion** [comment]
at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147517_a(SourceFile:20)

I don't use mob spawner renderers...something else must be doing this.

**Comment by Mithion** [comment]
Additional checks have been added in 1.4.0.009 to assist in preventing this.
