### ISSUE TITLE
Ars Magica 2 Potion ID conflicts

### ISSUE THREAD

**Issue by Juggerking** [Mithion/ArsMagica2#1103]
I'm running a 1.7.10 miinecraft server with ars magica 2(1.4.0.008) on it and serveral other mods, and when casting spells that buff, instead of getting the intended effects get vanilla buffs. I know this is caused because the Ars Magica Potion IDs begin at 256 which causes the array to start back at the beginning. Upon researching the issue I've seen that you've closed the issue several times saying that the ID's are now configurable, however when I look into the config files there are no configurations for the potion IDs. I was then wondering how do I do this? Or if already answered, where can I find the topic or post in which this is answered because after 2hours of googling I have yet to find a resolution to this issue.

Thank you in advance,
Juggerking

**Comment by Mithion** [comment]
Add this to your config if it isn't already there:

potions {
    I:agility=48
    I:astraldistortion=51
    I:burnoutredux=63
    I:charmed=39
    I:chronoanchor=41
    I:clarity=61
    I:entangled=43
    I:featherfall=34
    I:flight=33
    I:frostslow=40
    I:fury=53
    I:gravitywell=59
    I:haste=35
    I:illuminated=55
    I:leap=49
    I:levitation=60
    I:magicshield=38
    I:manaboost=50
    I:manaregen=42
    I:manashield=52
    I:regeneration=37
    I:scramblesynapses=54
    I:shrunken=62
    I:silence=46
    I:spellreflect=45
    I:swiftswim=47
    I:truesight=36
    I:waterbreathing=32
    I:waterygrave=44
}

**Comment by Juggerking** [comment]
I added it to the config file, but as it still conflicted(Illuminated was shruken) I edited the item IDs to empty slots (used NEI to get a potion ID list) but once cast it crashes my client and to get back onto the server I need to edit the player dat file. Is editing the IDs the root cause? And is there a fix?

I'd attach the crash report but it's 20 pages long, This bit seemed important so I'll include it;

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/28/15 10:48 PM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: -117
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

**Comment by Mithion** [comment]
If you changed a potion ID and it was applied to something, then you can get this crash - so yes, you are correct that you'd have to edit your NBT.

**Comment by Juggerking** [comment]
Is it normal that it continues to do that even if I recreate the spell and edited the NBT file?

**Comment by Mithion** [comment]
If the potion is on an NPC, then yes...mucking with potion IDs in an existing world is tricky.

**Comment by Mithion** [comment]
One thing you could try is to delete all entries in the potion section, but leave the outer section itself...try and let it regenerate.
You may run into the same conflicts as originally, though.  Make a backup first.

**Comment by Juggerking** [comment]
It was from casting a spell with self | light

**Comment by Juggerking** [comment]
Deleting all the entries in the potion section regenerates them in the same place that causes the initial error. My first thought was that the server would crash due to a mismatch between client and server potion IDs so I changed both and still got the crash, tried it in single player and got the same issue. Is there a way to change the IDs without a crash?

**Comment by ryukra** [comment]
The maximum limit of potion effect IDs is 127. you need to install something like DragonAPI to get 256. 256 is the maximum limit everything above that results in your error.

**Comment by sandalle** [comment]
Also see #1074 as this sounds like the same issue.

**Comment by Mithion** [comment]
#1074 has the solution.
