### ISSUE TITLE
Crash on startup dealing with buffs

### ISSUE THREAD

**Issue by sogortheogre** [Mithion/ArsMagica2#1133]
Updated DragonAPI / related mods, and am getting this crash now. There were some blockid conflicts with the buffs and the updated Rotarycraft, so I moved the buff block IDs to somewhere else. Could this be causing the error? I didn't think it would.

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 4/1/15 1:52 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 3028
	at net.minecraft.potion.Potion.<init>(Potion.java:68)
	at am2.buffs.ArsMagicaPotion.<init>(ArsMagicaPotion.java:14)
	at am2.buffs.BuffList.createAMPotion(BuffList.java:92)
	at am2.buffs.BuffList.Instantiate(BuffList.java:142)
	at am2.proxy.CommonProxy.preinit(CommonProxy.java:146)
	at am2.proxy.ClientProxy.preinit(ClientProxy.java:114)
	at am2.AMCore.preInit(AMCore.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.potion.Potion.<init>(Potion.java:68)
	at am2.buffs.ArsMagicaPotion.<init>(ArsMagicaPotion.java:14)
	at am2.buffs.BuffList.createAMPotion(BuffList.java:92)
	at am2.buffs.BuffList.Instantiate(BuffList.java:142)
	at am2.proxy.CommonProxy.preinit(CommonProxy.java:146)
	at am2.proxy.ClientProxy.preinit(ClientProxy.java:114)
	at am2.AMCore.preInit(AMCore.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 244690000 bytes (233 MB) / 726179840 bytes (692 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 116 mods loaded, 116 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	MobiusCore{1.2.4} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized
	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	STPPlugin{} [ServerTools|Permission Plugin] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Errored
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized
	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics2-rv2-beta-8.jar) Unloaded->Constructed->Pre-initialized
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0RC4} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC4-204.jar) Unloaded->Constructed->Pre-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed->Pre-initialized
	Forestry{3.5.0.481-unstable} [Forestry for Minecraft] (forestry_1.7.10-3.5.0.481-unstable.jar) Unloaded->Constructed->Pre-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized
	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.4-327.jar) Unloaded->Constructed->Pre-initialized
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized
	BetterChests{1.1.1.8} [BetterChests] (BetterChests-1.7.10-1.1.1.8.jar) Unloaded->Constructed->Pre-initialized
	betterstorage{0.12.0.124} [BetterStorage] (BetterStorage-1.7.10-0.12.0.124.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed->Pre-initialized
	BinnieCore{2.0-pre8} [Binnie Core] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	Botany{2.0-pre8} [Botany] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	ExtraBees{2.0-pre8} [Extra Bees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	ExtraTrees{2.0-pre8} [Extra Trees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	Genetics{2.0-pre8} [Genetics] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal(1).jar) Unloaded->Constructed->Pre-initialized
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.5.13.65} [ProjectRed] (ProjectRed-1.7.10-4.5.13.65-Base.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0RC4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC4-135.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized
	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V6b.jar) Unloaded->Constructed->Pre-initialized
	ChromatiCraft{Alpha} [ChromatiCraft] (ChromatiCraft 1.7.10 V6b.jar) Unloaded->Constructed->Errored
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	dynamictanks{1.0} [Dynamic Liquid Tanks 2.1] (dynamictanks-1.1.04.jar) Unloaded->Constructed->Pre-initialized
	EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO-1.7.10-2.2.8.349.jar) Unloaded->Constructed->Pre-initialized
	emashercore{1.3.0.1} [ET Resources] (EngineersToolbox-1.2.0.1-BETA.jar) Unloaded->Constructed->Pre-initialized
	emasherdefense{1.3.0.1} [ET Defense] (EngineersToolbox-1.2.0.1-BETA.jar) Unloaded->Constructed->Pre-initialized
	eng_toolbox{1.2.0.1} [Engineer's Toolbox] (EngineersToolbox-1.2.0.1-BETA.jar) Unloaded->Constructed->Pre-initialized
	gascraft{2.1.0.1} [GasCraft] (EngineersToolbox-1.2.0.1-BETA.jar) Unloaded->Constructed->Pre-initialized
	enhancedportals{3.0.10} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed->Pre-initialized
	extracells{2.2.55} [ExtraCells] (ExtraCells-1.7.10-2.2.55b85.jar) Unloaded->Constructed->Pre-initialized
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.2.2} [Extra Utilities] (extrautilities-1.2.2.jar) Unloaded->Constructed->Pre-initialized
	farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar) Unloaded->Constructed->Pre-initialized
	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized
	ForbiddenMagic{1.7.10-0.561} [Forbidden Magic] (Forbidden Magic-1.7.10-0.561.jar) Unloaded->Constructed->Pre-initialized
	ganysend{1.8.8} [Gany's End] (Ganys End-1.8.8.jar) Unloaded->Constructed->Pre-initialized
	ganysnether{1.7.8} [Gany's Nether] (Ganys Nether-1.7.8.jar) Unloaded->Constructed->Pre-initialized
	ganyssurface{1.9.5} [Gany's Surface] (Ganys Surface-1.9.5.jar) Unloaded->Constructed->Pre-initialized
	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized
	JABBA{1.2.0b} [JABBA] (Jabba-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized
	NetherOres{1.7.10R2.3.0RC3} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
	MapWriter{2.1.2} [MapWriter] (Opis-1.2.4a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Opis{1.2.4} [Opis] (Opis-1.2.4a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed->Pre-initialized
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized
	RotaryCraft{Gamma} [RotaryCraft] (RotaryCraft 1.7.10 V6b.jar) Unloaded->Constructed->Pre-initialized
	ReactorCraft{beta} [ReactorCraft] (ReactorCraft 1.7.10 V6a.jar) Unloaded->Constructed->Pre-initialized
	RIO{2.1} [RemoteIO] (RemoteIO-1.7.10-2.1.B0-universal.jar) Unloaded->Constructed->Pre-initialized
	Revamp{1.3.0} [Revamp] (Revamp-1.3.0.jar) Unloaded->Constructed->Pre-initialized
	Roguelike{1.3.6} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.jar) Unloaded->Constructed->Pre-initialized
	ServerTools{1.7.10-2.2.0.79} [ServerTools] (ServerTools-CORE-1.7.10-2.2.0.79.jar) Unloaded->Constructed->Pre-initialized
	ServerTools-PERMISSION{1.7.10-2.2.1.7} [ServerTools Permission] (ServerTools-PERMISSION-1.7.10-2.2.1.7.jar) Unloaded->Constructed->Pre-initialized
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{0.2.13.96} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.13.96.jar) Unloaded->Constructed->Pre-initialized
	torchLevers{1.4.1} [Torch Levers] (TorchLeversV1.4.1.jar) Unloaded->Constructed->Pre-initialized
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized
	TwilightForest{2.3.3} [The Twilight Forest] (twilightforest-1.7.10-2.3.3.jar) Unloaded->Constructed->Pre-initialized
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed->Pre-initialized
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded->Constructed->Pre-initialized
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized
	aobd{2.4.0} [Another One Bites The Dust] (AOBD-2.4.0.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
	CoFHCore: -[1.7.10]3.0.0RC4-204
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.0.0RC4-58
	ThermalExpansion: -[1.7.10]4.0.0RC4-135
	TConstruct Environment: Environment healthy.
	NetherOres: Lacking version information.
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 670/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TherminatorX** [comment]
See #1074

**Comment by sogortheogre** [comment]
Ahh, it was something more obvious than I thought at first. I was trying to rush things. I was correct in that I needed to change potionIDs, but I didn't realize that the potionIDs were more limited than the blockIDs.
