### ISSUE TITLE
Dispell Armor Imbuement crashes the game

### ISSUE THREAD

**Issue by sasuke0614** [Mithion/ArsMagica2#1142]
Hi mithion. 
I recently upgraded my battle mage leggins with the dispelling effect, but whenever it tries to remove an effect, the game crashes.
And thanks for your work, it's amazing !

Here is the bug repport : 
[15:58:41] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 4/13/15 3:58 PM
Description: Ticking player

java.lang.ClassCastException: net.minecraft.potion.Potion cannot be cast to java.lang.Boolean
	at am2.armor.infusions.Dispelling.applyEffect(Dispelling.java:50)
	at am2.armor.ArmorEventHandler.doInfusions(ArmorEventHandler.java:75)
	at am2.armor.ArmorEventHandler.onEntityLiving(ArmorEventHandler.java:26)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_296_ArmorEventHandler_onEntityLiving_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at am2.armor.infusions.Dispelling.applyEffect(Dispelling.java:50)
	at am2.armor.ArmorEventHandler.doInfusions(ArmorEventHandler.java:75)
	at am2.armor.ArmorEventHandler.onEntityLiving(ArmorEventHandler.java:26)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_296_ArmorEventHandler_onEntityLiving_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 258
	Entity Name: <PROFILE NAME>
	Entity's Exact location: 705.43, 64.00, 996.13
	Entity's Block location: World: (705,64,996), Chunk: (at 1,4,4 in 44,62; contains blocks 704,0,992 to 719,255,1007), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@5f633664
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.13.0-46-generic
	Java Version: 1.7.0_76, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 330008600 bytes (314 MB) / 3221749760 bytes (3072 MB) up to 5607260160 bytes (5347 MB)
	JVM Flags: 3 total; -Xms2048m -Xmx6016m -XX:PermSize=120m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 96
	FML: MCP v9.05 FML v7.10.88.1307 Minecraft Forge 10.13.2.1307 Optifine OptiFine_1.7.10_HD_B5 39 mods loaded, 39 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.88.1307} [Forge Mod Loader] (forge-1.7.10-10.13.2.1307-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1307} [Minecraft Forge] (forge-1.7.10-10.13.2.1307-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.3} [AnimationAPI] (AnimationAPI-1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DC1{3.4.2.19} [KingCore] ([1.7.2+] KingCore v3.4.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS1{3.2.1.26} [Arcane Scrolls] ([1.7.10] ArcaneScrolls v3.2.1.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EB{2.1.2.6} [Ender Book] ([1.7.2] EnderBook v2.1.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eplus{3.0.2-d} [Enchanting Plus] (Enchanting-Plus-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	rftl{1.7.10} [Rotten Flesh to Leather] (Forge SSP SMP - Rotten Flesh 1.7.2 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10 v6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mimicry{1.7.x_1067_1.0.3} [Mimicry] (Mimicry-1.7.x_1067_1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	xreliquary{1.2.DEV} [Reliquary] (Reliquary-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Roguelike{1.3.4} [Roguelike Dungeons] (roguelike-1.7.10-1.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_Ruins{13.4} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DP_SimpleFlight{0.8} [Simple Flight] (Simple-Flight-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.3} [Waila] (Waila-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	thirstmod{1.8.14} [Thirst Mod] (thirstmod-1.8.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/258, l='New World 1', x=705.43, y=64.00, z=996.13]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[15:58:41] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:354]: #@!@# Game crashed! Crash report saved to: #@!@# /home/chaboussie/MultiMC/instances/Magic World - Fantasy/minecraft/crash-reports/crash-2015-04-13_15.58.40-server.txt
[15:58:41] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[15:58:41] [Server thread/INFO]: Saving chunks for level 'New World 1'/Nether
[15:58:41] [Server thread/INFO]: Saving chunks for level 'New World 1'/The End
[15:58:41] [Server thread/INFO]: Saving chunks for level 'New World 1'/Wyvern Lair
[15:58:41] [Server thread/INFO]: Saving chunks for level 'New World 1'/Twilight Forest
[15:58:41] [Server thread/INFO] [journeymap]: Mapping halted in /home/chaboussie/MultiMC/instances/Magic World - Fantasy/minecraft/journeymap/data/sp/New World 1/DIM0
[15:58:41] [Server thread/INFO] [FML]: Unloading dimension 0
[15:58:41] [Server thread/INFO] [FML]: Unloading dimension -1
[15:58:41] [Server thread/INFO] [FML]: Unloading dimension 1
[15:58:41] [Server thread/INFO] [FML]: Unloading dimension -17
[15:58:41] [Server thread/INFO] [FML]: Unloading dimension 7
[15:58:41] [Server thread/INFO] [FML]: Applying holder lookups
[15:58:41] [Server thread/INFO] [FML]: Holder lookups applied
[15:58:41] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:58:41] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
Minecraft s'est arrété avec le code de d'arrêt 255.

**Comment by TherminatorX** [comment]
Looks more like a potion ID conflict to me.

**Comment by Mithion** [comment]
Not in this case; dispel is actually bugged.
I had it fixed in dev before passing the project to the new developer.

In the interim until it is released, I recommend removing the leggings using an NBT editor.
I released a short video showing how to do so:
https://www.youtube.com/watch?v=1u-HaadzSDA

**Comment by sasuke0614** [comment]
Thanks ! And for the Appropriation spell ? 
You should have heard of it ? do you plan on fixing it ? 
In my case, the games tells me that the block has been cleared, but it tells me that every time i cast the spell..
Tthanks anyway :)

**Comment by Mithion** [comment]
what about appropriation?  I don't see anything in the original post about it.
I know something along the lines of it breaks when you try to use nether blocks or something.

**Comment by Mithion** [comment]
Corrected in 1.4.0.009 dev.
