### ISSUE TITLE
Network exception in console logs

### ISSUE THREAD

**Issue by LemADEC** [Mithion/ArsMagica2#1221]
Every now and then, there's an exception in the console, seems related to Network:
```
[01:25:05] [Client thread/INFO] [inventorytweaks/]: am2.containers.ContainerObelisk
[01:25:40] [Client thread/TRACE] [FML/]: Ars Magica 2 >> Located Power Node list for chunk -13, 0
[01:25:40] [Client thread/TRACE] [FML/]: Ars Magica 2 >> Successfully registered power node at {-203, 86, 13}
[01:25:40] [Client thread/ERROR] [FML/]: NetworkEventFiringHandler exception
java.lang.NullPointerException
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:193) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.sendToAllAround(FMLEventChannel.java:151) [FMLEventChannel.class:?]
	at am2.network.AMNetHandler.sendPacketToAllClientsNear(AMNetHandler.java:109) [AMNetHandler.class:?]
	at am2.network.AMNetHandler.sendObeliskUpdate(AMNetHandler.java:297) [AMNetHandler.class:?]
	at am2.blocks.tileentities.TileEntityObelisk.sendCookUpdateToClients(TileEntityObelisk.java:176) [TileEntityObelisk.class:?]
	at am2.blocks.tileentities.TileEntityObelisk.func_145845_h(TileEntityObelisk.java:218) [TileEntityObelisk.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[01:25:51] [Client thread/INFO] [inventorytweaks/]: am2.guis.GuiObelisk
[01:25:51] [Client thread/INFO] [inventorytweaks/]: am2.containers.ContainerObelisk
```

This happens with am2-1.4.0.008.

**Comment by LemADEC** [comment]
Issue seems related from alternating with SMP and SSP, maybe some data not being reset when on WorldUnload event or something?
