### ISSUE TITLE
New entity code for bosses causes crash when run on the server

### ISSUE THREAD

**Issue by DoomFruit** [Mithion/ArsMagica2#1254]
I installed AM2 on a server which I run, and the moment someone spawned in a water guardian, it crashed with this error:

```
[15:12:20] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.boss.EntityDragonPart.func_70016_h(DDD)V
        at am2.bosses.AM2Boss.func_70071_h_(AM2Boss.java:194) ~[AM2Boss.class:?]
        at am2.bosses.EntityWaterGuardian.func_70071_h_(EntityWaterGuardian.java:108) ~[EntityWaterGuardian.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
```

The function here, func_70016_h, is Entity.setVelocity - which is marked as @SideOnly(Side.CLIENT) - this is probably why it didn't show up in testing, since it would run just fine in single player.

**Comment by DoomFruit** [comment]
Found a fix, it was just a simple "isRemote" check. I'll fire off a pull request shortly.
