### ISSUE TITLE
Ticking Block Entity: net.minecraft.item.ItemMonsterPlacer cannot be cast to am2.items.ItemCrystalPhylactery

### ISSUE THREAD

**Issue by DrasticDemise** [Mithion/ArsMagica2#1373]
Yampst collected a pretty weird crash report that you may or may not be interested in. The pack is running the latest build here, however the crash that this was collected from was a heavily modified version of my pack, so this may just be garbage from another mod outside of my control.

### Comments by pack administrator:

> minecraft itemMonsterPlacer is attempting to be casted to Am2.items.ItemCrystalPhylactery

### Full crash report:

    ---- Minecraft Crash Report ----
    // Everything's going to plan. No, really, that was supposed to happen.
    
    Time: 1/15/16 8:25 AM
    Description: Ticking block entity
    
    java.lang.ClassCastException: net.minecraft.item.ItemMonsterPlacer cannot be cast to am2.items.ItemCrystalPhylactery
    	at am2.blocks.tileentities.TileEntityInertSpawner.func_145845_h(TileEntityInertSpawner.java:185)
    	at net.minecraft.world.World.func_72939_s(World.java:1939)
    	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- Head --
    Stacktrace:
    	at am2.blocks.tileentities.TileEntityInertSpawner.func_145845_h(TileEntityInertSpawner.java:185)
    
    -- Block entity being ticked --
    Details:
    	Name: TileEntityInertSpawner // am2.blocks.tileentities.TileEntityInertSpawner
    	Block type: ID #458 (tile.arsmagica2:inertSpawner // am2.blocks.BlockInertSpawner)
    	Block data value: 0 / 0x0 / 0b0000
    	Block location: World: (121,78,342), Chunk: (at 9,4,6 in 7,21; contains blocks 112,0,336 to 127,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    	Actual block type: ID #458 (tile.arsmagica2:inertSpawner // am2.blocks.BlockInertSpawner)
    	Actual block data value: 0 / 0x0 / 0b0000
    Stacktrace:
    	at net.minecraft.world.World.func_72939_s(World.java:1939)
    	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    
    -- Affected level --
    Details:
    	Level name: Survival
    	All players: 1 total; [EntityPlayerMP['ZexyZek'/291, l='Survival', x=119.91, y=78.00, z=341.22]]
    	Chunk stats: ServerChunkCache: 454 Drop: 0
    	Level seed: 3885704834608933406
    	Level generator: ID 00 - default, ver 1. Features enabled: true
    	Level generator options: 
    	Level spawn location: World: (56,64,252), Chunk: (at 8,4,12 in 3,15; contains blocks 48,0,240 to 63,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    	Level time: 218540 game time, 50380 day time
    	Level dimension: 1
    	Level storage version: 0x04ABD - Anvil
    	Level weather: Rain time: 13002 (now: false), thunder time: 76381 (now: false)
    	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
    Stacktrace:
    	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    
    -- System Details --
    Details:
    	Minecraft Version: 1.7.10
    	Operating System: Windows 7 (x86) version 6.1
    	Java Version: 1.8.0_66, Oracle Corporation
    	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    	Memory: 134424008 bytes (128 MB) / 460103680 bytes (438 MB) up to 523501568 bytes (499 MB)
    	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 21 mods loaded, 21 mods active
    	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
    	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    	UCHIJAAAA	sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1 (1).jar) 
    	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
    	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (AM2-1.4.0.009-Dev.jar) 
    	UCHIJAAAA	claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar) 
    	UCHIJAAAA	lootablebodies{1.3.6} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.7.10-backport_1.3.6.jar) 
    	UCHIJAAAA	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
    	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
    	UCHIJAAAA	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
    	UCHIJAAAA	RadixCore{2.0.0} [RadixCore] (RadixCore-1.7.10-2.0.0-universal.jar) 
    	UCHIJAAAA	MCA{5.0.3} [Minecraft Comes Alive] (MCA-5.0.3-1.7.10-universal.jar) 
    	UCHIJAAAA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
    	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
    	UCHIJAAAA	TooMuchTNT{2.9} [TooMuchTNT] (TooMuchTNT v2.9.jar) 
    	UCHIJAAAA	yampst{1.3.5} [YAMPST] (Yampst-Simply Magic-1.0.0.jar) 
    	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
    	Profiler Position: N/A (disabled)
    	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	Player Count: 1 / 8; [EntityPlayerMP['ZexyZek'/291, l='Survival', x=119.91, y=78.00, z=341.22]]
    	Type: Integrated Server (map_client.txt)
    	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by jjtParadox** [comment]
Confirmed, this is due to vanilla AM2 from a mechanic that I just dug up.

There's a ritual that turns a vanilla mob spawner into an AM2 "Inert Spawner", which can take a phylactery and presumably do something with said phylactery every tick.

However, if a player puts in anything besides a phylactery, the spawner tries to tick that item as a phylactery and fails.

Looks like the wrong method was used to prevent a player from putting a non-phylactery in, but that should be easily fixable.

**Comment by iotachaos** [comment]
@jjtParadox @Mithion 
this is not fixes in AM2 1.4.0.009 (Updated February 8, 2016)
