### ISSUE TITLE
[1.4.0.009] - Server Crashing after a few minutes of playing after i updated the mod

### ISSUE THREAD

**Issue by kulemada** [Mithion/ArsMagica2#1450]
Today i updated the ars magica 2 mod on my server on an already excisting world and after a few minutes of playing it crashed and gave me an error:

java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.getOres(Ljava/lang/String;Z)Ljava/util/List;
	at am2.blocks.BlockDesertNova.func_149854_a(BlockDesertNova.java:45)
	at net.minecraft.block.Block.canSustainPlant(Block.java:1912)
	at net.minecraft.block.BlockBush.func_149718_j(BlockBush.java:65)
	at am2.blocks.AMFlower.canGrowOn(AMFlower.java:49)
	at am2.worldgen.AM2FlowerGen.func_76484_a(AM2FlowerGen.java:28)
	at am2.worldgen.AM2WorldDecorator.generateFlowers(AM2WorldDecorator.java:143)
	at am2.worldgen.AM2WorldDecorator.generateOverworld(AM2WorldDecorator.java:103)
	at am2.worldgen.AM2WorldDecorator.generate(AM2WorldDecorator.java:88)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:130)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1165)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:249)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:169)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408)
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121)
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:212)
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:305)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:413)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:591)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

**Comment by jjtParadox** [comment]
What version of forge are you using? We recommend build 1492, as that is what AM2 is built against.

**Comment by jjtParadox** [comment]
@kulemada any update for this issue?
