### ISSUE TITLE
AM2 crashed after click oculus

### ISSUE THREAD

**Issue by yeyifangg** [Mithion/ArsMagica2#1463]
I found that my AM2 levels and skills have been resets after changeworld
it‘s said that this bug has been fixed in AM 2 1.4.0.009,so i updated it 
and client throw this after clicking oculus
java.lang.NullPointerException: Unexpected error
	at am2.guis.GuiSkillTrees.func_73866_w_(GuiSkillTrees.java:102)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at am2.proxy.ClientProxy.openSkillTreeUI(ClientProxy.java:188)
	at am2.blocks.BlockOcculus.func_149727_a(BlockOcculus.java:59)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:112)

**Comment by jjtParadox** [comment]
Try using forge 1492, otherwise the compendiumunlocks folder in your .minecraft directory.
(Possible duplicate of #1448, but discussion there seemed to die off)

**Comment by jjtParadox** [comment]
@yeyifangg any update for this issue?
