### ISSUE TITLE
Critical error (doesn't affect the gameplay or the mod but still an error)

### ISSUE THREAD

**Issue by agronaque512** [Mithion/ArsMagica2#1470]
When i start my server tell me that they were a critical error. It doesn't change anything (i think) cause i can play with. Here is the error:
`[20:15:01] [main/ERROR]: A critical problem occurred registering the ASM transformer class am2.preloader.AccessTransformers
java.lang.IllegalArgumentException: resource AM2_at.cfg not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[guava-16.0.jar:?]
	at com.google.common.io.Resources.getResource(Resources.java:229) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:118) ~[forge-1.7.10-10.13.4.1558-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101) ~[forge-1.7.10-10.13.4.1558-1.7.10.jar:?]
	at am2.preloader.AccessTransformers.<init>(AccessTransformers.java:10) ~[AccessTransformers.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_77]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.11.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:108) [forge-1.7.10-10.13.4.1558-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]`

**Comment by jjtParadox** [comment]
This can be ignored (and might be fixed with a newer version of Forge, but can't confirm).
