### ISSUE TITLE
I dont know what went wrong, i got this crash in mine craft: there was a severe problem with mod loading

### ISSUE THREAD

**Issue by CrystalPanda** [Mithion/ArsMagica2#1490]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 5/18/16 12:20 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.OutOfMemoryError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at org.lwjgl.BufferUtils.createByteBuffer(BufferUtils.java:60)
	at shadersmodcore.client.ShadersTex.getIntBuffer(ShadersTex.java:67)
	at shadersmodcore.client.ShadersTex.updateDynTexSubImage1(ShadersTex.java:347)
	at shadersmodcore.client.ShadersTex.updateDynamicTexture(ShadersTex.java:333)
	at net.minecraft.client.renderer.texture.DynamicTexture.func_110564_a(SourceFile:35)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(SourceFile:18)
	at net.malisis.core.renderer.font.MalisisFont.loadTexture(MalisisFont.java:710)
	at net.malisis.core.renderer.font.MalisisFont.<init>(MalisisFont.java:125)
	at net.malisis.core.renderer.font.MalisisFont.<init>(MalisisFont.java:102)
	at net.malisis.doors.proxy.ClientProxy.initFonts(ClientProxy.java:102)
	at net.malisis.doors.MalisisDoors.postInit(MalisisDoors.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 75551472 bytes (72 MB) / 387588096 bytes (369 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -Xms256m -XX:PermSize=192m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJ	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJ	oresheepmod{v3.1.0} [Ore Sheep] (1.7.10-OreSheepMod-v3.1.0.jar) 
	UCHIJ	movillages{1.4} [Mo' Villages] ([1.7.10]MoVillages-1.4.jar) 
	UCHIJ	ChickenShed{1.1.3} [Chicken Shed] ([1.7.2] ChickenShed (v1.1.3).jar) 
	UCHIJ	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJ	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJ	animalbikes{1.7.10} [Animal Bikes] (AnimalBikes_1.7.10.jar) 
	UCHIJ	aquacreeper{1.0b} [Aqua Creeper] (AquaCreeper-1.0b.jar) 
	UCHIJ	BaMsGRAVE{1.4.2_01} [BaM's Grave] (bamsgrave-1.7.2-1.4.2_01.jar) 
	UCHIJ	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
	UCHIJ	blockrevenge{1.0} [Revenge of the Blocks] (BlockRevenge-v1.0-1.7.10.jar) 
	UCHIJ	CamouflageCreepers{1.4} [Camouflage Creepers] (CamouflageCreepers-1.7.10-1.4.jar) 
	UCHIJ	climatecontrol{0.4} [Climate Control] (ClimateControl-0.5.beta53.jar) 
	UCHIJ	colorfularmor{1.7.10-2.6} [Colorful Armor] (colorfularmor-1.7.10-2.6.jar) 
	UCHIJ	MineTweaker3{3.0.7} [MineTweaker 3] (CraftTweaker-Customized-1.7.10-3.0.7.jar) 
	UCHIJ	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCHIJ	EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
	UCHIJ	etfuturum{1.5.5} [Et Futurum] (Et Futurum-1.5.5.jar) 
	UCHIJ	exoticbirds{1.0} [Exotic Birds] (Exotic Birds 1.7.10 - 1.0.3b.jar) 
	UCHIJ	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCHIJ	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJ	fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
	UCHIJ	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
	UCHIJ	FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
	UCHIJ	FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
	UCHIJ	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJ	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJ	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJ	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJ	hungryanimals{1.7.10-10.13.2.1291-1.0.4.2} [Hungry Animals] (hungryanimals-1.7.10-2.0.alpha01.jar) 
	UCHIJ	hungryZombies{1.2.0} [Hungry Zombies] (hungryzombies-1.7.10-1.2.0.jar) 
	UCHIJ	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJ	InventoryPets{1.4.3} [Inventory Pets] (inventorypets-1.7.10-1.4.3-universal.jar) 
	UCHIJ	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJ	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHIJ	LLadders{0.5.0} [Luppii's Ladders] (Ladders-0.5.0-MC1.7.10.jar) 
	UCHIJ	reaper_lantern{1.47} [Lantern mod] (Lantern1.47[1.7.10].jar) 
	UCHIJ	MagicYarn{1.1.5} [Magic Yarn] (MagicYarn-1.7.10.jar) 
	UCHIJ	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIE	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJ	mesa{1.7.10-R2} [Movement Enhancement Suits and Armor] (MESA-1.7.10-R2.jar) 
	UCHIJ	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJ	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.0-1.jar) 
	UCHIJ	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJ	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJ	pandorasbox{2.0.1} [Pandora's Box] (PandorasBox-2.1.jar) 
	UCHIJ	Photoptics{0.1.1.3c} [Photoptics] (Photoptics-0.1.1.3c.jar) 
	UCHIJ	PigManure{1.0.1} [Pig Manure] (pig-manure-1.0.1.jar) 
	UCHIJ	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
	UCHIJ	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCHIJ	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.7.10.jar) 
	UCHIJ	stacywolves{1.0.6-1.7.10} [Stacy's Wolves Mod] (Stacy'sWolvesMod-1.7.10-1.0.6.jar) 
	UCHIJ	StacyPlaysMod{1.0.0} [StacyPlaysMod] (stacyplays_mod_1.7.10.zip) 
	UCHIJ	StellarAPI{0.1.1.5} [Stellar API] (Stellar API-0.1.1.5.jar) 
	UCHIJ	StorageDrawers{1.7.10-1.9.7} [Storage Drawers] (StorageDrawers-1.7.10-1.9.7.jar) 
	UCHIJ	ultimate_unicorn_mod{1.4.10} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.7.10-1.4.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 8400GS/PCIe/SSE2' 

If anyone knows what happened then please help.

**Comment by Kolatra** [comment]
Your game ran out of memory, provide it with more RAM in your launcher. It's not an Ars Magica 2 issue at all.

**Comment by CrystalPanda** [comment]
@Kolatra thank you so much idk how to use github so sorry i just was confused and needed help
