### ISSUE TITLE
All Spell Effect Crash

### ISSUE THREAD

**Issue by LunaticPanda** [Mithion/ArsMagica2#1497]
On my server, we have a little custom made "mod pack". Basically, whenever someone shoots **any** type of spell at one person, that person crashes and I have to /effect [player] clear. It only happens to one player. Here is the crash report that she sent me. We're using version 009.

java.lang.NullPointerException: Ticking entity
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

We reset her playerdata and I looked at the configs to see any potion id clashes and there is none.

**Comment by ThatOneTraitor** [comment]
Err, im pretty sure a modlist would help out alot.

**Comment by LunaticPanda** [comment]
Oh I completely forgot about the modlist ._.
Pastebin: [http://pastebin.com/pg1xf434](url)
ModList: 1.7.10_AM2 - 1.4.0.009, AnimationAPI - 1.7.10 - 1.2.4, BiblioCraft[v1.11.4][MC1.7.10], iChunUtil-4.1.0, Morph-Beta - 0.9.2, twilightforest-1.7.10 - 2.3.7, weaponmod - 1.14.3, witchery-1.7.10-0.24.1

**Comment by ThatOneTraitor** [comment]
thats a... really small pack you have there. Maybe drop it into a zip and ill check what mod its being incompatible with

**Comment by ThatOneTraitor** [comment]
erm... ya closed this... was that intentional or did you click comment and close?

**Comment by LunaticPanda** [comment]
@ThatOneTraitor Yeah it was an accident lol

Here is the zip: [http://www.mediafire.com/download/5lhy1k4dkfw23y4/Mysidia+Mods.zip](url)

**Comment by jjtParadox** [comment]
Most potion errors are caused by potion ID conflicts, mind looking into your configs to make sure you don't have conflicting IDs?

**Comment by ThatOneTraitor** [comment]
I'll check, got my pc back so i can do stuff now ^.^

**Comment by ThatOneTraitor** [comment]
Ok, first of all you didnt put the entire modpack in. eh and second, I know for a fact that witchery and am2 have potion id conflicts by default. may wanna install the more potion id's mod and rearrange the id's. if your gonna use the mod just get all the ars magica effects and add 150 to their ID's, that'll work

**Comment by ThatOneTraitor** [comment]
@LunaticPanda any update?

**Comment by LunaticPanda** [comment]
Er...What mod should I use?

**Comment by jjtParadox** [comment]
You don't need to use any specific mod, you just need to modify the configuration settings for the mods so that their potion IDs are not the same. I recommend googling how to fix potion ID conflicts, you'll find some guides that will walk you through it.

**Comment by LunaticPanda** [comment]
Thx

**Comment by ghost** [comment]
I have a modpack running AM2, Witchery, and Thaumcraft all together, And whenever I step in Taint from Thaumcraft, the client crashes. I am getting near to the exact same crash report as mentioned in the first post of this. I cannot find the location to modify the potion Id's for Thaumcraft. I have installed the Extended Potions mod aswell.

**Comment by jjtParadox** [comment]
@revoltinstyle you will need to change potion IDs in at least two of those mods. If you cannot find how to change it in Thaumcraft, change it in AM2 and Witchery. Both have configs for potion IDs. Google has some guides on how to do this.
