### ISSUE TITLE
Crash if a potion effect gets applied 

### ISSUE THREAD

**Issue by Ryius** [Mithion/ArsMagica2#1557]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 27.08.16 19:02
Description: Ticking entity

java.lang.NoSuchFieldError: field_149433_c
    at net.minecraft.network.play.server.S1DPacketEntityEffect.<init>(SourceFile:24)
    at net.minecraft.entity.player.EntityPlayerMP.func_70670_a(EntityPlayerMP.java:891)
    at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:642)
    at net.minecraft.entity.projectile.EntityPotion.func_70184_a(SourceFile:96)
    at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:192)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at WorldServerOF.func_72870_g(WorldServerOF.java:347)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.network.play.server.S1DPacketEntityEffect.<init>(SourceFile:24)
    at net.minecraft.entity.player.EntityPlayerMP.func_70670_a(EntityPlayerMP.java:891)
    at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:642)
    at net.minecraft.entity.projectile.EntityPotion.func_70184_a(SourceFile:96)
    at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:192)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at WorldServerOF.func_72870_g(WorldServerOF.java:347)
    at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
    Entity Type: ThrownPotion (net.minecraft.entity.projectile.EntityPotion)
    Entity ID: 9304
    Entity Name: entity.ThrownPotion.name
    Entity's Exact location: 231,69, 67,05, 242,69
    Entity's Block location: World: (231,67,242), Chunk: (at 7,4,2 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0,20, -0,51, 0,03
Stacktrace:
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
    Level name: Test 2
    All players: 1 total; [EntityPlayerMP['Ryius'/299, l='Test 2', x=231,50, y=66,00, z=242,50]]
    Chunk stats: ServerChunkCache: 4226 Drop: 0
    Level seed: -546428620631598513
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (240,64,252), Chunk: (at 0,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 479 game time, 479 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 85533 (now: false), thunder time: 54427 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1030699872 bytes (982 MB) / 1965826048 bytes (1874 MB) up to 17072521216 bytes (16281 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 12 mods loaded, 12 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   AM2-Preloader{0.0.3} [AMCore](minecraft.jar) 
    UCHIJAAAA   <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCHIJAAAA   FastCraft{1.23} [FastCraft](fastcraft-1.23 %281%29.jar) 
    UCHIJAAAA   ChunkAnimator{@VERSION@} [Chunk Animator](ChunkAnimator-MC1.7.10-1.0.1 %282%29.jar) 
    UCHIJAAAA   mcheli{1.0.2} [MC Helicopter](mcheli) 
    UCHIJAAAA   worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   arsmagica2{1.4.0.009} [Ars Magica 2](1.7.10_AM2-1.4.0.009 %283%29.jar) 
    UCHIJAAAA   DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V15a.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Ryius'/299, l='Test 2', x=231,50, y=66,00, z=242,50]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.7.10_HD_U_D6
    Render Distance Chunks: 32
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    OpenGlVersion: 4.5.0 NVIDIA 372.54
    OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8

**Comment by jjtParadox** [comment]
Generally potion crashes happen because of conflicting potion IDs. Can you check to make sure you don't have any conflicting IDs?

**Comment by Ryius** [comment]
i dont. i have some mods checking for id conflicts

**Comment by jjtParadox** [comment]
Where is the DragonAPI .jar file? It's either in the mods folder or the mods/1.7.10 folder.

**Comment by Ryius** [comment]
mods/1.7.10 folder

**Comment by Ryius** [comment]
is this causing any trouble

**Comment by jjtParadox** [comment]
Move it to the mods folder, as the 1.7.10 folder is not being searched by AM2 in v.009
