### ISSUE TITLE
[1.4.0.009] Game crash at startup

### ISSUE THREAD

**Issue by Nefar1on** [Mithion/ArsMagica2#1564]
This error only happens after i add AM2 to my modpack, without AM2 the game runs perfectly fine.
__________________________
[crash-2016-09-27_11.50.14-client.txt](https://github.com/Mithion/ArsMagica2/files/494437/crash-2016-09-27_11.50.14-client.txt)

[11:50:14] [Client thread/INFO] [ArsMagica2]: Core: Altering definition of net.minecraft.client.renderer.entity.RendererLivingEntity,  (obfuscated)
[11:50:15] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: 
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 27/09/16 11:50 AM
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78480_b(F)V @443: iload_2
  Reason:
    Type 'net/minecraft/client/multiplayer/WorldClient' (current frame, locals[2]) is not assignable to integer
  Current Frame:
    bci: @443
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, 'net/minecraft/client/multiplayer/WorldClient', integer }
    stack: { 'net/minecraft/client/renderer/EntityRenderer', float }
  Bytecode:
    0x0000000: 2ab4 00db b404 4113 0443 b604 482a b400
    0x0000010: 989a 003a b804 4db8 0452 bb04 5459 2ab4
    0x0000020: 00db b704 554d 2a2c b500 efb2 045b 2cb5
    0x0000030: 045e b804 6110 40a0 000f b804 6410 20a0
    0x0000040: 0007 04b8 0468 2a04 b500 98b8 046b 2ab4
    0x0000050: 00db b401 a94d 2cc6 009c b804 6ec6 006c
    0x0000060: 1304 7013 0470 1304 72b6 0478 1304 7a13
    0x0000070: 047c b604 784e bb01 2859 b701 292d b601
    0x0000080: 2f13 047e b601 2fb8 046e b601 2fb6 0136
    0x0000090: 3a04 bb04 8059 bb01 2859 b701 2913 0482
    0x00000a0: b601 2f19 04b6 012f 1304 84b6 012f b601
    0x00000b0: 36b7 0486 3a05 2ab4 00db b404 8ab6 0490
    0x00000c0: 1905 b604 9601 b804 99b8 049c 9900 2703
    0x00000d0: b804 68bb 0480 5913 049e 03bd 0004 b804
    0x00000e0: a4b7 0486 4e2a b400 dbb4 048a b604 902d
    0x00000f0: b604 962a b400 dbb4 0294 c104 a699 0011
    0x0000100: 2a2a b400 dbb4 0294 c004 a6b7 04aa 2ab4
    0x0000110: 009a 2ca5 001d 2ab4 009a 2cb8 04b0 b804
    0x0000120: b32a 09b5 00a0 2a03 b500 a22a 2cb5 009a
    0x0000130: b804 b69a 0009 b804 b999 0007 04a7 0004
    0x0000140: 03b3 04be b204 c2b8 04c5 b604 ca2a b403
    0x0000150: fb99 0008 2a23 b704 cc2a b400 dbb4 0441
    0x0000160: b604 cfb8 04d4 3e1d 9a00 3d2a b400 dbb4
    0x0000170: 0183 b404 d799 0030 2ab4 00db b401 83b4
    0x0000180: 04da 9900 0a04 b802 a39a 001c b800 ca2a
    0x0000190: b400 cc65 1404 db94 9e00 142a b400 dbb6
    0x00001a0: 04df a700 0a2a b800 cab5 00cc 2ab4 00db
    0x00001b0: b404 4113 04e1 b604 482a 231c b804 e53d
    0x00001c0: 2ab4 00db b404 e899 00cf 1d99 00cb 2ab4
    0x00001d0: 00db b404 ecb6 04f1 2ab4 00db b401 83b4
    0x00001e0: 018b 1301 8c6a 1301 8d62 3804 1704 1704
    0x00001f0: 6a17 046a 1301 8e6a 3805 2ab4 00db b404
    0x0000200: ecb4 04f4 8617 056a 3806 2ab4 00db b404
    0x0000210: ecb4 04f7 8617 056a 3807 0436 082a b400
    0x0000220: dbb4 0183 b404 fa99 0006 0236 082a b400
    0x0000230: dbb4 0183 b401 8899 004d 2a59 b401 9017
    0x0000240: 0662 b501 902a 59b4 0199 1707 62b5 0199
    0x0000250: 232a b401 9d66 3809 2a23 b501 9d2a b401
    0x0000260: 9717 096a 3806 2ab4 019b 1709 6a38 072a
    0x0000270: b400 dbb4 01a5 1706 1707 1508 866a b604
    0x0000280: fea7 0015 2ab4 00db b401 a517 0617 0715
    0x0000290: 0886 6ab6 04fe 2ab4 00db b404 41b6 04cf
    0x00002a0: 2ab4 00db b405 019a 02c7 2ab4 00db b401
    0x00002b0: 83b4 0373 b305 03bb 0505 592a b400 db2a
    0x00002c0: b400 dbb4 0146 2ab4 00db b401 49b7 0508
    0x00002d0: 3a04 1904 b605 0b36 0519 04b6 050e 3606
    0x00002e0: b805 1115 0568 2ab4 00db b401 466c 3607
    0x00002f0: 1506 b805 1415 0668 2ab4 00db b401 496c
    0x0000300: 6404 6436 082a b400 dbb4 0183 b405 1736
    0x0000310: 092a b400 dbb4 01a9 c601 302a b400 dbb4
    0x0000320: 0441 1305 19b6 0448 2ab4 00db b605 1c99
    0x0000330: 0017 2a23 2ab4 051e 1305 1f15 096c 8561
    0x0000340: b605 23a7 0009 2a23 09b6 0523 b201 1399
    0x0000350: 002c 2ab4 0108 c600 1a11 1702 b803 6cb8
    0x0000360: 03bd b803 6f2a b401 0823 b605 26b8 03cd
    0x0000370: 2ab4 00db b601 4004 b605 2b2a b805 30b5
    0x0000380: 051e 2ab4 00db b404 4113 0532 b605 352a
    0x0000390: b400 dbb4 0183 b403 c099 000d 2ab4 00db
    0x00003a0: b402 94c6 0098 1102 0413 01c5 b805 392a
    0x00003b0: b400 dbb4 0183 b405 3c36 0ab8 053f 9a00
    0x00003c0: 0e2a b400 dbb4 0183 03b5 053c 2ab4 00db
    0x00003d0: b404 8a23 2ab4 00db b402 94c6 0007 04a7
    0x00003e0: 0004 0315 0715 08bb 0541 5913 0543 2a03
    0x00003f0: b705 463a 0b19 0b23 b805 4cb6 0550 bb05
    0x0000400: 4159 1305 522a 03b7 0546 3a0c 190c 23b8
    0x0000410: 0555 2ab4 00db b401 8315 0ab5 053c 2ab4
    0x0000420: 00db b401 83b4 0558 9900 132a b400 dbb4
    0x0000430: 0183 b405 5b9a 0006 b805 5e2a b400 dbb4
    0x0000440: 0441 b604 cfa7 0033 0303 2ab4 00db b401
    0x0000450: 462a b400 dbb4 0149 b805 6211 1701 b803
    0x0000460: 6cb8 036f 1117 00b8 036c b803 6f2a b605
    0x0000470: 652a b805 30b5 051e 2ab4 00db b402 94c6
    0x0000480: 00ef 1101 00b8 0568 bb05 4159 1305 6a2a
    0x0000490: 03b7 0546 3a0d 190d 23b8 056d 0336 0ab2
    0x00004a0: 0570 b602 5499 0030 b205 7407 bd00 0459
    0x00004b0: 032a b400 dbb4 0294 5359 0415 07b8 057a
    0x00004c0: 5359 0515 08b8 057a 5359 0623 b805 7f53
    0x00004d0: b805 8336 0a15 0a9a 0012 2ab4 00db b402
    0x00004e0: 9415 0715 0823 b605 89b2 058c 07bd 0004
    0x00004f0: 5903 2ab4 00db b402 9453 5904 1507 b805
    0x0000500: 7a53 5905 1508 b805 7a53 5906 23b8 057f
    0x0000510: 53b8 0583 57a7 0059 3a0a 190a 1305 8eb8
    0x0000520: 0594 3a0e 190e 1305 96b6 059a 3a0f 190f
    0x0000530: 1305 9cbb 000d 592a b705 9fb6 05a5 190f
    0x0000540: 1305 a7bb 000b 592a 1507 1508 b705 aab6
    0x0000550: 05a5 190f 1305 acbb 0009 592a 1904 b705
    0x0000560: afb6 05a5 bb05 b159 190e b705 b4bf 2ab7
    0x0000570: 05b7 2ab7 05ba 2ab4 00db b401 83b4 055b
    0x0000580: 2ab4 00ba 9f00 1f2a 2ab4 00db b401 83b4
    0x0000590: 05bd b500 bc2a 2ab4 00db b401 83b4 055b
    0x00005a0: b500 ba2a b400 dbb4 0183 b405 5b99 001b
    0x00005b0: 2a2a b400 dbb4 0441 b405 c02a b400 dbb4
    0x00005c0: 0441 b405 c3b7 05c7 2ab4 00db b401 83b4
    0x00005d0: 05ca 9900 0e2a b400 dbb4 0183 04b5 05bd
    0x00005e0: b1                                     
  Exception Handler Table:
    bci [1180, 1301] => handler: 1304
  Stackmap Table:
    append_frame(@70,Object[#1108])
    chop_frame(@75,1)
    append_frame(@201,Object[#444])
    same_frame(@243)
    same_frame(@270)
    same_frame(@304)
    same_frame(@316)
    same_frame(@320)
    same_locals_1_stack_item_frame(@321,Integer)
    same_frame(@345)
    append_frame(@396,Integer)
    same_frame(@421)
    same_frame(@428)
    full_frame(@557,{Object[#2],Float,Integer,Integer,Float,Float,Float,Float,Integer},{})
    same_frame_extended(@644)
    full_frame(@662,{Object[#2],Float,Integer,Integer},{})
    full_frame(@838,{Object[#2],Float,Integer,Integer,Object[#1285],Integer,Integer,Integer,Integer,Integer},{})
    same_frame(@844)
    same_frame(@880)
    same_frame(@891)
    same_frame(@934)
    append_frame(@972,Integer)
    full_frame(@994,{Object[#2],Float,Integer,Integer,Object[#1285],Integer,Integer,Integer,Integer,Integer,Integer},{Object[#1164],Float})
    full_frame(@995,{Object[#2],Float,Integer,Integer,Object[#1285],Integer,Integer,Integer,Integer,Integer,Integer},{Object[#1164],Float,Integer})
    chop_frame(@1083,1)
    same_frame(@1096)
    same_frame(@1144)
    full_frame(@1237,{Object[#2],Float,Integer,Integer,Object[#1285],Integer,Integer,Integer,Integer,Integer,Integer,Top,Top,Object[#1345]},{})
    same_frame(@1257)
    full_frame(@1304,{Object[#2],Float,Integer,Integer,Object[#1285],Integer,Integer,Integer,Integer,Integer,Top,Top,Top,Object[#1345]},{Object[#1085]})
    full_frame(@1390,{Object[#2],Float,Integer,Integer},{})
    same_frame(@1443)
    same_frame(@1480)
    same_frame(@1504)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 733798728 bytes (699 MB) / 1179648000 bytes (1125 MB) up to 2863661056 bytes (2731 MB)
	Mod Pack: ~~ERROR~~ NullPointerException: null
	LiteLoader Mods: ~~ERROR~~ NullPointerException: null
	LaunchWrapper: 35 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: am2.preloader.BytecodeTransformers
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: openmods.core.OpenModsClassTransformer
          - Transformer: openblocks.asm.OpenBlocksClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: lumien.randomthings.Transformer.RTClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	U	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	U	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	U	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	U	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	U	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	U	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar) 
	U	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	U	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	U	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	U	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	U	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	U	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	U	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	U	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	U	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	U	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	U	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	U	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	U	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	U	fodc{1.6.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.6.1.jar) 
	U	origin{8.0.3} [Origin] (Origin-1.7.10-8.0.3.jar) 
	U	addonscrewdriver{1.0.0} [OriginAddonScrewdriver] (Origin-1.7.10-8.0.3.jar) 
	U	ProjectE{1.7.10-PE1.10.0} [ProjectE] (ProjectE-1.7.10-PE1.10.0.jar) 
	U	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	U	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	U	Translocator{1.1.2.16} [Translocator] (Translocator-1.7.10-1.1.2.16-universal.jar) 
	U	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	U	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	U	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 7600M Series'
	Launched Version: 1.7.10 - Modded
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7600M Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Fanver_Modded_Universal_v1.3.5_mc1.7.x.zip, Sphax Modded 64x MC17]
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 8
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
	OpenGlRenderer: AMD Radeon HD 7600M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by Nefar1on** [comment]
#1560 
moving all mods out of that folder that wer'nt put there automatically solved this issue.
