### ISSUE TITLE
Launcher Not starting

### ISSUE THREAD

**Issue by ZenWolf151** [Mithion/ArsMagica2#1625]
Whenever i include ars magica in my modpack, even if its a  fresh clean install of minecraft, it crashes before the launcher can even fully initialize. im using the last released version for 1.7.10. THis didnt start happening until after my java updated, so im wondering, if that might be the issue? id so, what java should i install? Using java 8 update 131

**Comment by TheIcyOne** [comment]
It would be helpful to have the crash report.

**Comment by ZenWolf151** [comment]
This is the latest install with a clean install of MC and forge, and all the mods thrown in. It will launch just fine until Ars magica 2 is put in. any info as to why you can give me, is appreciated

[08:42:37] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:42:37] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:42:37] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[08:42:37] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[08:42:37] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[08:42:37] [main/WARN]: The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:37] [main/INFO]: Core initializing...stand back!  I'm going to try MAGIC!
[08:42:37] [main/INFO]: [AppEng] Core Init
[08:42:37] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:38] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:40] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[08:42:42] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[08:42:44] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[08:42:46] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[08:42:46] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_D8.jar
[08:42:46] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:42:46] [main/INFO]: Loading tweaker net.minecraftxray.loader.XRayTweaker from XRay-Mod-All-Versions-1.10.2.jar
[08:42:46] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:42:46] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[08:42:46] [main/INFO]: Loading tweak class name net.minecraftxray.loader.XRayTweaker
[08:42:46] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[08:42:46] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:42:46] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:42:46] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[08:42:46] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[08:42:46] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[08:42:46] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[08:42:46] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/C:/Users/Zen%20Wolf/AppData/Roaming/.minecraft/mods/OptiFine_1.7.10_HD_U_D8.jar
[08:42:46] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: C:\Users\Zen Wolf\AppData\Roaming\.minecraft\mods\OptiFine_1.7.10_HD_U_D8.jar
[08:42:46] [main/INFO]: Calling tweak class net.minecraftxray.loader.XRayTweaker
[08:42:46] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[08:42:48] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/ERROR]: A critical problem occurred registering the ASM transformer class am2.preloader.AccessTransformers
java.lang.IllegalArgumentException: resource AM2_at.cfg not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[guava-17.0.jar:?]
	at com.google.common.io.Resources.getResource(Resources.java:229) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:118) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at am2.preloader.AccessTransformers.<init>(AccessTransformers.java:10) ~[AccessTransformers.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at java.lang.Class.newInstance(Class.java:438) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:108) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[08:42:48] [main/INFO]: Core: Located OptiFine in OptiFine_1.7.10_HD_U_D8.jar. We'll to confirm that...
[08:42:48] [main/INFO]: Core: Located Thaumcraft in Thaumcraft-1.7.10-4.2.3.5.jar
[08:42:48] [main/INFO]: Core: Located Thaumcraft in thaumcraftneiplugin-1.7.10-1.7a.jar
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Finished data injection.
[08:42:48] [main/INFO]: Finished data injection.
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Extracted library EJML-core-0.26.jar.
[08:42:48] [main/INFO]: Loaded library EJML-core-0.26.jar.
[08:42:48] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:48] [main/INFO]: Attempting to detect JVM version...
[08:42:48] [main/INFO]: Detected JVM: 1.8
[08:42:48] [main/INFO]: Starting library configuration...
[08:42:48] [main/INFO]: [info.inpureprojects.core.API.Utils.Downloader:download:19]: Downloading: http://files.inpureprojects.info/libs/commons-codec-1.9.jar
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.net.UnknownHostException: files.inpureprojects.info
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.Socket.connect(Socket.java:589)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.Socket.connect(Socket.java:538)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1167)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1103)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:987)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:985)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:984)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:931)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URL.openStream(URL.java:1038)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1460)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at info.inpureprojects.core.API.Utils.Downloader.download(Downloader.java:20)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at info.inpureprojects.core.Preloader.INpurePreLoader.injectData(INpurePreLoader.java:80)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:119)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:42:49] [main/INFO]: [info.inpureprojects.core.API.Utils.Downloader:download:19]: Downloading: http://files.inpureprojects.info/libs/commons-compress-1.8.1.jar
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.net.UnknownHostException: files.inpureprojects.info
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.Socket.connect(Socket.java:589)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.Socket.connect(Socket.java:538)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1167)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1103)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:987)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:985)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:984)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:931)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URL.openStream(URL.java:1038)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1460)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at info.inpureprojects.core.API.Utils.Downloader.download(Downloader.java:20)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at info.inpureprojects.core.Preloader.INpurePreLoader.injectData(INpurePreLoader.java:80)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:119)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[08:42:49] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:42:49] [main/INFO]: System attached to FML. Now intercepting all logging calls.
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/WARN]: openmods.config.simple.ConfigProcessor.process(ConfigProcessor.java:108): Adding new values: '[activate_gl_capabilities_hook, activate_player_render_hook, activate_map_gen_fix, activate_movement_callback, activate_stencil_patches]'
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[08:42:49] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:50] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:50] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:50] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:50] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[08:42:50] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[08:42:50] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[08:42:50] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[08:42:50] [main/INFO]: CraftingTweaks will now patch func_146274_d in bdw...
[08:42:50] [main/INFO]: CraftingTweaks successfully patched func_146274_d in bdw!
[08:42:50] [main/INFO]: Core: Altering definition of net.minecraft.world.World,  (obfuscated)
[08:42:50] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: Method mutation failed: did not find cpw/mods/fml/common/eventhandler/EventBus.post / (Lcpw/mods/fml/common/eventhandler/Event;)Z
	at factorization.coremod.AbstractAsmMethodTransform$MutateCall.apply(AbstractAsmMethodTransform.java:141) ~[Factorization-1.7.10-0.8.88.8.8888g.jar:?]
	at factorization.coremod.ASMTransformer.applyTransform(ASMTransformer.java:146) ~[Factorization-1.7.10-0.8.88.8.8888g.jar:?]
	at factorization.coremod.ASMTransformer.applyTransform(ASMTransformer.java:121) ~[Factorization-1.7.10-0.8.88.8.8888g.jar:?]
	at factorization.coremod.ASMTransformer.transform(ASMTransformer.java:107) ~[Factorization-1.7.10-0.8.88.8.8888g.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
[08:42:50] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[08:42:50] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[08:42:50] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[08:42:50] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[08:42:50] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:968)
[08:42:50] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[08:42:50] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
