### ISSUE TITLE
AM2 1.7.10 crash w/ Fire Guardian Entity

### ISSUE THREAD

**Issue by Th4nat0s1s** [Mithion/ArsMagica2#1649]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 9/6/17 5:45 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: am2/bosses/EntityFireGuardian
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: am2/bosses/EntityFireGuardian
	at am2.entities.EntityManager.registerEntities(EntityManager.java:106)
	at am2.proxy.CommonProxy.init(CommonProxy.java:138)
	at am2.AMCore.init(AMCore.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 5 more
Caused by: java.lang.ClassNotFoundException: am2.bosses.EntityFireGuardian
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 34 more
Caused by: java.lang.RuntimeException: Error in getCommonSuperClass("am2/particles/AMParticle", "java/util/List"): 
	at com.forgeessentials.core.preloader.asminjector.ASMClassWriter.getCommonSuperClass(ASMClassWriter.java:54)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
	at com.forgeessentials.core.preloader.EventTransformer.transform(EventTransformer.java:45)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 36 more
Caused by: java.lang.ClassNotFoundException: net/minecraft/client/particle/EntityFX
	at com.forgeessentials.core.preloader.asminjector.ASMUtil.loadClassNode(ASMUtil.java:127)
	at com.forgeessentials.core.preloader.asminjector.ASMUtil.getClassNode(ASMUtil.java:81)
	at com.forgeessentials.core.preloader.asminjector.ASMUtil.loadSuperClassNode(ASMUtil.java:133)
	at com.forgeessentials.core.preloader.asminjector.ASMClassWriter.getCommonSuperClass(ASMClassWriter.java:42)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2059763536 bytes (1964 MB) / 2359296000 bytes (2250 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms2048M -Xmx4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	infinitefluids{1.0.1} [InfiniteFluids] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHE	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHI	forgecreeperheal{1.1.1} [Forge Creeper Heal 1.1.1] ([1.7.10]ForgeCreeperHeal-1.1.1.jar) 
	UCHI	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCHI	BuildCraft|Core{7.1.22} [BuildCraft] (buildcraft-7.1.22.jar) 
	UCHI	BuildCraft|Transport{7.1.22} [BC Transport] (buildcraft-7.1.22.jar) 
	UCHI	BuildCraft|Silicon{7.1.22} [BC Silicon] (buildcraft-7.1.22.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHI	WailaAddonBC{1.0.5.1} [WailaAddonBC] ([1.7.10]WailaAddonBC-1.0.5.1.jar) 
	UCHI	levelup{0.4} [Level Up!] (_Level-Up-Mod-1.7.10.jar) 
	UCHI	BuildCraft|Factory{7.1.22} [BC Factory] (buildcraft-7.1.22.jar) 
	UCHI	BuildCraft|Robotics{7.1.22} [BC Robotics] (buildcraft-7.1.22.jar) 
	UCHI	BuildCraft|Energy{7.1.22} [BC Energy] (buildcraft-7.1.22.jar) 
	UCHI	BuildCraft|Builders{7.1.22} [BC Builders] (buildcraft-7.1.22.jar) 
	UCHI	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHI	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHI	ForgeEssentials{1.4.5} [Forge Essentials] (forgeessentials-1.7.10-1.4.5.1330-server.jar) 
	UCHI	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHI	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.37.jar) 
	UCHI	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar) 
	CoFHCore: -[1.7.10]3.1.3-327
	ForgeEssentials: Running ForgeEssentials 1.4.5.1330 (2090585). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by TheIcyOne** [comment]
What were you doing at the time?

**Comment by Th4nat0s1s** [comment]
Just trying to start my server, anyways, it seemed to be an issue with Forge Essentials, I rolled back from v1330 to v1187 and now everything is working fine... I have no idea why though...

These are the lines that lead me to this conclusion, if you would like to see more of the log let me know...

[17:45:24] [Server thread/ERROR] [FML/ForgeEssentials]: Exception caught during firing event com.forgeessentials.util.events.FEModuleEvent$FEModuleServerStoppedEvent@57b46921:
java.lang.RuntimeException: Tried to access DataManager before its initialization

**Comment by TheIcyOne** [comment]
Oh, I completely missed that. Unfortunately, it's unlikely you'll be able to use more recent versions of ForgeEssentials as it has a few weird calls that interact badly with AM2's weird cods, especially since 1.7.10 versions of AM2 and probably ForgeEssentials have been out of development for around a year now.
