### ISSUE TITLE
Mod incompatibility (1.7.10) (RESOLVED)

### ISSUE THREAD

**Issue by Bluestar1215** [Mithion/ArsMagica2#1664]
Every time i load up Minecraft with the following mods installed:
Treecapitator, and all of the mods needed to run it
Ars Magica 2, and all the mods needed to run that
Extrautilities
Optifine
Journeymap
Galacticraft, all the mods needed to run it
Tinkerers Construct, and all the mods needed to run it
Twilight forest
witchery
Worltedit (client)

It crashes. i have tried uninstalling every mod but AM2, and it runs fine. before, it had an issue with witchery and its potion IDs. I fixed that. every time it starts loading the sound system it crashes. I think it might be a problem with one of the mods here. 

(Crash report)

[net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 8/29/18 6:27 AM
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78480_b(F)V @381: iload_2
  Reason:
    Type 'net/minecraft/world/World' (current frame, locals[2]) is not assignable to integer
  Current Frame:
    bci: @381
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, 'net/minecraft/world/World', integer }
    stack: { 'net/minecraft/client/renderer/EntityRenderer', float }
  Bytecode:
    0x0000000: 2ab4 00db b404 4313 0445 b604 4a2a b400
    0x0000010: 989a 0026 b804 4fb8 0454 bb04 5659 2ab4
    0x0000020: 00db b704 574d 2a2c b500 efb2 045d 2cb5
    0x0000030: 0460 2a04 b500 98b8 0463 2ab4 00db b401
    0x0000040: a54d 2cc6 0072 b804 66c6 006c 1304 6813
    0x0000050: 046a 1304 6cb6 0472 1304 7413 0476 b604
    0x0000060: 724e bb01 2459 b701 252d b601 2b13 0478
    0x0000070: b601 2bb8 0466 b601 2bb6 0132 3a04 bb04
    0x0000080: 7a59 bb01 2459 b701 2513 047c b601 2b19
    0x0000090: 04b6 012b 1304 7eb6 012b b601 32b7 0480
    0x00000a0: 3a05 2ab4 00db b404 84b6 048a 1905 b604
    0x00000b0: 9001 b804 932a b400 dbb4 028b c104 9799
    0x00000c0: 0011 2a2a b400 dbb4 028b c004 97b7 049b
    0x00000d0: 2ab4 009a 2ca5 001d 2ab4 009a 2cb8 04a1
    0x00000e0: b804 a42a 09b5 00a0 2a03 b500 a22a 2cb5
    0x00000f0: 009a b804 a79a 0009 b804 aa99 0007 04a7
    0x0000100: 0004 03b3 04af b204 b3b8 04b6 b604 bc2a
    0x0000110: b403 f999 0008 2a23 b704 be2a b400 dbb4
    0x0000120: 0443 b604 c1b8 04c6 3e1d 9a00 3d2a b400
    0x0000130: dbb4 017f b404 c999 0030 2ab4 00db b401
    0x0000140: 7fb4 04cc 9900 0a04 b802 9a9a 001c b800
    0x0000150: ca2a b400 cc65 1404 cd94 9e00 142a b400
    0x0000160: dbb6 04d1 a700 0a2a b800 cab5 00cc 2ab4
    0x0000170: 00db b404 4313 04d3 b604 4a2a 231c b804
    0x0000180: d73d 2ab4 00db b404 da99 00cf 1d99 00cb
    0x0000190: 2ab4 00db b404 deb6 04e3 2ab4 00db b401
    0x00001a0: 7fb4 0187 1301 886a 1301 8962 3804 1704
    0x00001b0: 1704 6a17 046a 1301 8a6a 3805 2ab4 00db
    0x00001c0: b404 deb4 04e6 8617 056a 3806 2ab4 00db
    0x00001d0: b404 deb4 04e9 8617 056a 3807 0436 082a
    0x00001e0: b400 dbb4 017f b404 ec99 0006 0236 082a
    0x00001f0: b400 dbb4 017f b401 8499 004d 2a59 b401
    0x0000200: 8c17 0662 b501 8c2a 59b4 0195 1707 62b5
    0x0000210: 0195 232a b401 9966 3809 2a23 b501 992a
    0x0000220: b401 9317 096a 3806 2ab4 0197 1709 6a38
    0x0000230: 072a b400 dbb4 01a1 1706 1707 1508 866a
    0x0000240: b604 f0a7 0015 2ab4 00db b401 a117 0617
    0x0000250: 0715 0886 6ab6 04f0 2ab4 00db b404 43b6
    0x0000260: 04c1 2ab4 00db b404 f39a 0245 2ab4 00db
    0x0000270: b401 7fb4 0371 b304 f5bb 04f7 592a b400
    0x0000280: db2a b400 dbb4 0142 2ab4 00db b401 45b7
    0x0000290: 04fa 3a04 1904 b604 fd36 0519 04b6 0500
    0x00002a0: 3606 b805 0315 0568 2ab4 00db b401 426c
    0x00002b0: 3607 1506 b805 0615 0668 2ab4 00db b401
    0x00002c0: 456c 6404 6436 082a b400 dbb4 017f b405
    0x00002d0: 0936 092a b400 dbb4 01a5 c600 c22a b400
    0x00002e0: dbb4 0443 1305 0bb6 044a 2ab4 00db b605
    0x00002f0: 0e99 0017 2a23 2ab4 0510 1305 1115 096c
    0x0000300: 8561 b605 15a7 0009 2a23 09b6 0515 b201
    0x0000310: 1399 002c 2ab4 0108 c600 1a11 1702 b803
    0x0000320: 6ab8 03bb b803 6d2a b401 0823 b605 18b8
    0x0000330: 03cb 2ab4 00db b601 3c04 b605 1d2a b805
    0x0000340: 22b5 0510 2ab4 00db b404 4313 0524 b605
    0x0000350: 272a b400 dbb4 017f b403 be99 000d 2ab4
    0x0000360: 00db b402 8bc6 002a 1102 0413 01c1 b805
    0x0000370: 2b2a b400 dbb4 0484 232a b400 dbb4 028b
    0x0000380: c600 0704 a700 0403 1507 1508 b605 2f2a
    0x0000390: b400 dbb4 0443 b604 c1a7 0033 0303 2ab4
    0x00003a0: 00db b401 422a b400 dbb4 0145 b805 3311
    0x00003b0: 1701 b803 6ab8 036d 1117 00b8 036a b803
    0x00003c0: 6d2a b605 362a b805 22b5 0510 2ab4 00db
    0x00003d0: b402 8bc6 00db 1101 00b8 0539 0336 0ab2
    0x00003e0: 053c b602 5099 0030 b205 4007 bd00 0459
    0x00003f0: 032a b400 dbb4 028b 5359 0415 07b8 0546
    0x0000400: 5359 0515 08b8 0546 5359 0623 b805 4b53
    0x0000410: b805 4f36 0a15 0a9a 0012 2ab4 00db b402
    0x0000420: 8b15 0715 0823 b605 55b2 0558 07bd 0004
    0x0000430: 5903 2ab4 00db b402 8b53 5904 1507 b805
    0x0000440: 4653 5905 1508 b805 4653 5906 23b8 054b
    0x0000450: 53b8 054f 57a7 0059 3a0a 190a 1305 5ab8
    0x0000460: 0560 3a0b 190b 1305 62b6 0566 3a0c 190c
    0x0000470: 1305 68bb 000d 592a b705 6bb6 0571 190c
    0x0000480: 1305 73bb 000b 592a 1507 1508 b705 76b6
    0x0000490: 0571 190c 1305 78bb 0009 592a 1904 b705
    0x00004a0: 7bb6 0571 bb05 7d59 190b b705 80bf 2ab7
    0x00004b0: 0583 2ab7 0586 2ab4 00db b401 7fb4 0589
    0x00004c0: 2ab4 00ba 9f00 1f2a 2ab4 00db b401 7fb4
    0x00004d0: 058c b500 bc2a 2ab4 00db b401 7fb4 0589
    0x00004e0: b500 ba2a b400 dbb4 017f b405 8999 001b
    0x00004f0: 2a2a b400 dbb4 0443 b405 8f2a b400 dbb4
    0x0000500: 0443 b405 92b7 0596 2ab4 00db b401 7fb4
    0x0000510: 0599 9900 0e2a b400 dbb4 017f 04b5 058c
    0x0000520: b1                                     
  Exception Handler Table:
    bci [988, 1109] => handler: 1112
  Stackmap Table:
    same_frame(@55)
    append_frame(@181,Object[#1173])
    same_frame(@208)
    same_frame(@242)
    same_frame(@254)
    same_frame(@258)
    same_locals_1_stack_item_frame(@259,Integer)
    same_frame(@283)
    append_frame(@334,Integer)
    same_frame(@359)
    same_frame(@366)
    full_frame(@495,{Object[#2],Float,Object[#1173],Integer,Float,Float,Float,Float,Integer},{})
    same_frame_extended(@582)
    full_frame(@600,{Object[#2],Float,Object[#1173],Integer},{})
    full_frame(@776,{Object[#2],Float,Object[#1173],Integer,Object[#1271],Integer,Integer,Integer,Integer,Integer},{})
    same_frame(@782)
    same_frame(@818)
    same_frame(@829)
    same_frame(@872)
    full_frame(@903,{Object[#2],Float,Object[#1173],Integer,Object[#1271],Integer,Integer,Integer,Integer,Integer},{Object[#1158],Float})
    full_frame(@904,{Object[#2],Float,Object[#1173],Integer,Object[#1271],Integer,Integer,Integer,Integer,Integer},{Object[#1158],Float,Integer})
    same_frame(@911)
    same_frame(@924)
    same_frame(@972)
    append_frame(@1045,Integer)
    same_frame(@1065)
    full_frame(@1112,{Object[#2],Float,Object[#1173],Integer,Object[#1271],Integer,Integer,Integer,Integer,Integer},{Object[#1087]})
    full_frame(@1198,{Object[#2],Float,Object[#1173],Integer},{})
    same_frame(@1251)
    same_frame(@1288)
    same_frame(@1312)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 102892728 bytes (98 MB) / 234881024 bytes (224 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_C1 22 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
		Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
		AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
		CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
		Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
		NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal (2).jar) 
		arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
		bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
		Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
		AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
		AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10.jar) 
		ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
		GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
		GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
		journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
		Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
		harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
		TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-Mod-1.7.10.jar) 
		TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
		witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
		worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6530D'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6530D GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TheIcyOne** [comment]
What did you do to fix the witchery incompatibility? The only mod there that I don't know for a fact has been played alongside AM2 is WorldEdit, so try cutting that out.

**Comment by Bluestar1215** [comment]
I changed the potion IDs
they were having a conflict with AM2
But thanks for the info! ill tell you if removing WD it will work

**Comment by Bluestar1215** [comment]
seems like Not enough items is incompatible with AM2. after i removed it the crashes stopped.
maybe you could write that down on a log or something? I didn't even list it because i thought it was so minor.
Edit: seems like the crash log is from optifine. but NEI is incompatible too.
Edit 2: I forgot to thank you for your help! keep on making AM2 awesome!

**Comment by TheIcyOne** [comment]
NEI is definitely compatible with AM2, I didn't notice Optifine though, that tends to be the cause of pretty much every modded issue.

**Comment by kutschkem** [comment]
Sooooo, can this issue be closed then?

**Comment by TheIcyOne** [comment]
Mithion isn't around anymore, so the only way this is getting closed is if the author closes it themself.
