### ISSUE TITLE
World gen error, conflict with JinRyu DBCmod

### ISSUE THREAD

**Issue by RXVega8** [Mithion/ArsMagica2#1668]
Hai, i am having issues, i dont know how to fix it, here's the log:Hai, i am having issues, i dont know how to fix it, here's the log:

java.lang.NullPointerException: Exception in server tick loop at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398) at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52) at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398) at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52) at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398) at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52) at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170) at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125) at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:120) at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:121) at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20) at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12) at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343) at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:130) at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Please help :C

**Comment by SSKirillSS** [comment]
How is this related to AM2?
