### ISSUE TITLE
Help my minecraft crashes.

### ISSUE THREAD

**Issue by gabe234124213** [Mithion/ArsMagica2#1678]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 11/01/20 02:13 PM
Description: Initializing game

java.lang.VerifyError: get long/double overflows locals
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78471_a(FJ)V @429: dload
  Reason:
    Local index 17 is invalid
  Bytecode:
    0x0000000: b803 8136 0415 0499 000c 2ab4 00e4 2320
    0x0000010: b805 c323 3805 2ab4 00e4 b404 3713 0439
    0x0000020: b604 3e2a b403 e799 0008 2a23 b704 ca11
    0x0000030: 0b44 b803 d411 0b71 b803 d411 0bc0 b803
    0x0000040: d411 0204 1301 ccb8 0533 2ab4 00e4 b401
    0x0000050: a8c7 0011 2ab4 00e4 2ab4 00e4 b401 acb5
    0x0000060: 01a8 2ab4 00e4 b404 3713 05c5 b605 2f2a
    0x0000070: 23b6 05c7 2ab4 00e4 b401 a83a 062a b400
    0x0000080: e4b4 038d 3a07 2ab4 00e4 b405 cb3a 0819
    0x0000090: 06b4 05ce 1906 b401 b519 06b4 05ce 6723
    0x00000a0: 8d6b 6339 0919 06b4 05d1 1906 b401 be19
    0x00000b0: 06b4 05d1 6723 8d6b 6339 0b19 06b4 05d4
    0x00000c0: 1906 b401 c119 06b4 05d4 6723 8d6b 6339
    0x00000d0: 0d2a b400 e4b4 0437 1305 d6b6 052f 0336
    0x00000e0: 0f15 0f05 a207 7815 0f36 102a b400 e4b4
    0x00000f0: 018a b403 3599 001f 150f b305 dcb2 05dc
    0x0000100: 9a00 0d03 0404 03b8 05e0 a700 0a04 0303
    0x0000110: 03b8 05e0 1504 9900 0905 2320 b805 e42a
    0x0000120: b400 e4b4 0437 1305 e6b6 052f 1504 9900
    0x0000130: 1903 032a b400 e4b4 014d 2ab4 00e4 b401
    0x0000140: 50b8 05e9 a700 1603 032a b400 e4b4 014d
    0x0000150: 2ab4 00e4 b401 50b8 054a 2a23 b705 ec11
    0x0000160: 4100 b805 5015 0499 0006 b805 ef11 0b44
    0x0000170: b803 d42a b400 e4b4 0437 1305 f1b6 052f
    0x0000180: 2a23 150f b605 f315 0499 0007 23b8 05f6
    0x0000190: 2ab4 00e4 b401 ac2a b400 e4b4 018a b403
    0x00001a0: 9605 a000 0704 a700 0403 b805 fa18 11b2
    0x00001b0: 05fd 8d63 3911 1809 b206 008d 6339 0918
    0x00001c0: 0bb2 0603 8d63 390b 2ab4 00e4 b404 3713
    0x00001d0: 0605 b605 2fb8 060b 57b8 060e 9a00 0fb8
    0x00001e0: 0611 9a00 09b8 0614 9900 35b2 0617 9a00
    0x00001f0: 2f2a 0223 b706 1a2a b400 e4b4 0437 1306
    0x0000200: 1cb6 052f 1504 9900 06b8 061f 1907 23b6
    0x0000210: 0622 1504 9900 0fb8 0625 a700 0911 0be2
    0x0000220: b803 bf11 0b60 b803 d42a 0423 b706 1a2a
    0x0000230: b400 e4b4 018a b406 2899 0009 111d 01b8
    0x0000240: 062b 2ab4 00e4 b404 3713 062d b605 2fbb
    0x0000250: 062f 59b7 0630 3a13 1504 9900 0e19 1318
    0x0000260: 0918 0b18 0db8 0634 1913 1809 180b 180d
    0x0000270: b606 372a b400 e4b4 038d 1913 23b6 063b
    0x0000280: 150f 9a00 5fb8 0381 9900 06b8 063e 2a59
    0x0000290: b406 4004 60b5 0640 2ab4 00e4 b404 3713
    0x00002a0: 0642 b605 2f2a b400 e4b4 038d 1906 03b6
    0x00002b0: 0646 9a00 2620 0994 9900 2020 b805 2a65
    0x00002c0: 3714 1614 0994 9b00 1216 1414 0647 949e
    0x00002d0: 0006 a700 06a7 ffd0 b803 8199 0006 b806
    0x00002e0: 4b19 06b4 01be 1406 4c98 9c00 0a2a 1907
    0x00002f0: 23b7 0651 2ab4 00e4 b404 3713 0653 b605
    0x0000300: 2f2a 0323 b706 1a11 0b60 b803 d42a b400
    0x0000310: e4b6 00ec b206 58b6 03ca b806 5d2a b400
    0x0000320: e4b4 0437 1306 5fb6 052f 1117 00b8 032e
    0x0000330: b803 89b8 0381 9900 06b8 0662 1907 1906
    0x0000340: 0323 8db6 0666 57b8 0381 9900 06b8 0669
    0x0000350: 111d 00b8 062b 1102 0413 01cc b805 33b2
    0x0000360: 066d b606 7036 162a b402 929a 0111 1117
    0x0000370: 00b8 032e b803 afb8 0389 b806 732a b400
    0x0000380: e4b4 0437 1306 75b6 052f 1516 9900 14b2
    0x0000390: 0678 04bd 0004 5903 03b8 055d 53b8 067c
    0x00003a0: 1907 1906 1913 23b6 0680 1516 9900 14b2
    0x00003b0: 0678 04bd 0004 5903 02b8 055d 53b8 067c
    0x00003c0: b806 5d2a 238d b603 ac11 1700 b803 2eb8
    0x00003d0: 03af b803 892a b400 e4b4 0200 c600 a019
    0x00003e0: 06b2 02d0 b606 8499 0095 1906 c102 f199
    0x00003f0: 008d 2ab4 00e4 b401 8ab4 039c 9a00 8019
    0x0000400: 06c0 02f1 3a17 110b c0b8 03bf 2ab4 00e4
    0x0000410: b404 3713 0686 b605 2f15 1699 003e b206
    0x0000420: 8910 06bd 0004 5903 1907 5359 0419 1753
    0x0000430: 5905 2ab4 00e4 b402 0053 5906 03b8 055d
    0x0000440: 5359 0719 17b4 068d b606 9353 5908 23b8
    0x0000450: 0562 53b8 0696 9a00 202a b400 e4b4 018a
    0x0000460: b403 9c9a 0013 1907 1917 2ab4 00e4 b402
    0x0000470: 0003 23b6 069a 110b c0b8 03d4 1117 00b8
    0x0000480: 032e b803 af2a b400 cd0f 979a 00aa 1906
    0x0000490: c102 f199 00a2 2ab4 00e4 b401 8ab4 039c
    0x00004a0: 9a00 952a b400 e4b4 0200 c600 8b19 06b2
    0x00004b0: 02d0 b606 849a 0080 1906 c002 f13a 1711
    0x00004c0: 0bc0 b803 bf2a b400 e4b4 0437 1306 86b6
    0x00004d0: 052f 1516 9900 3eb2 0689 1006 bd00 0459
    0x00004e0: 0319 0753 5904 1917 5359 052a b400 e4b4
    0x00004f0: 0200 5359 0603 b805 5d53 5907 1917 b406
    0x0000500: 8db6 0693 5359 0823 b805 6253 b806 969a
    0x0000510: 0020 2ab4 00e4 b401 8ab4 039c 9a00 1319
    0x0000520: 0719 172a b400 e4b4 0200 0323 b606 9a11
    0x0000530: 0bc0 b803 d42a b400 e4b4 0437 1306 9cb6
    0x0000540: 052f 110b e2b8 03d4 1103 0204 0403 b806
    0x0000550: 9f19 07b2 06a5 1906 23b6 06a9 110b e2b8
    0x0000560: 03bf 2ab4 0292 9a00 5a2a 238d b603 a02a
    0x0000570: b400 e4b4 0437 1306 abb6 052f 1504 9900
    0x0000580: 06b8 06ae 1908 1906 23b6 06b2 b806 5d2a
    0x0000590: 0323 b706 1a2a b400 e4b4 0437 1306 b4b6
    0x00005a0: 052f 1504 9900 06b8 06b7 1908 1906 23b6
    0x00005b0: 06ba 1504 9900 06b8 06bd 2a23 8db6 03ac
    0x00005c0: 03b8 06c0 110b 44b8 03d4 2ab4 00e4 b404
    0x00005d0: 3713 06c2 b605 2f15 0499 0006 b806 c52a
    0x00005e0: 23b6 06c8 1504 9900 06b8 06cb 04b8 06c0
    0x00005f0: 1504 9900 0c2a 2305 b806 cfb8 06d2 110b
    0x0000600: e2b8 03bf 110b 44b8 03d4 1103 0211 0303
    0x0000610: 0403 b806 9f11 0204 1301 ccb8 0533 2a03
    0x0000620: 23b7 061a 110b e2b8 03d4 03b8 06c0 2ab4
    0x0000630: 00e4 b600 ecb2 0658 b603 cab8 06d7 b806
    0x0000640: da99 009c 2ab4 00e4 b404 3713 06dc b605
    0x0000650: 2f2a b400 e4b4 018a b406 2899 0009 111d
    0x0000660: 01b8 062b 110b e2b8 03d4 1103 0211 0303
    0x0000670: 0403 b806 9f2a b400 e4b4 018a b403 3599
    0x0000680: 0036 b205 dc9a 000d 0304 0404 b805 e0a7
    0x0000690: 000a 0403 0304 b805 e015 0499 0006 b806
    0x00006a0: df19 0704 238d b606 e357 1504 9900 22b8
    0x00006b0: 06e6 a700 1c15 0499 0006 b806 df19 0704
    0x00006c0: 238d b606 e357 1504 9900 06b8 06e6 110b
    0x00006d0: e2b8 03bf 111d 00b8 062b a700 292a b400
    0x00006e0: e4b4 0437 1306 dcb6 052f 1504 9900 06b8
    0x00006f0: 06df 1907 0423 8db6 06e3 5715 0499 0006
    0x0000700: b806 e6b8 06e9 1516 9900 4e2a b402 929a
    0x0000710: 0047 b806 732a b400 e4b4 0437 1306 75b6
    0x0000720: 052f b206 7804 bd00 0459 0304 b805 5d53
    0x0000730: b806 7c2a b400 e4b4 038d 1906 1913 23b6
    0x0000740: 0680 b206 7804 bd00 0459 0302 b805 5d53
    0x0000750: b806 7cb8 065d 04b8 06c0 110b 44b8 03d4
    0x0000760: 110b e2b8 03bf 110b 60b8 03bf 1906 b401
    0x0000770: be14 064c 2ab4 00e4 b401 8ab4 06ec 1303
    0x0000780: 366a 8d63 979b 0017 2ab4 00e4 b404 3713
    0x0000790: 06ee b605 2f2a 1907 23b7 0651 1516 9900
    0x00007a0: 262a b400 e4b4 0437 1306 f0b6 052f b206
    0x00007b0: f305 bd00 0459 0319 0753 5904 23b8 0562
    0x00007c0: 53b8 067c 2ab4 00e4 b404 3713 06f5 b605
    0x00007d0: 2fb2 06f8 06bd 0004 5903 2ab4 00e4 b403
    0x00007e0: 8d53 5904 23b8 0562 5359 0515 0fb8 055d
    0x00007f0: 53b8 0696 3618 1518 9a00 3e2a b400 cd0f
    0x0000800: 979a 0035 b206 179a 002f 1504 9900 0d2a
    0x0000810: 2315 10b8 06fb b806 fe11 0100 b805 5015
    0x0000820: 0499 000e 2a17 0515 10b8 0701 a700 0a2a
    0x0000830: 2315 0fb6 0703 1504 9900 06b8 0706 2ab4
    0x0000840: 00e4 b401 8ab4 0335 9a00 0e2a b400 e4b4
    0x0000850: 0437 b604 cdb1 840f 01a7 f888 0404 0403
    0x0000860: b805 e02a b400 e4b4 0437 b604 cdb1     
  Stackmap Table:
    append_frame(@19,Integer)
    append_frame(@47,Float)
    same_frame(@98)
    full_frame(@225,{Object[#2],Float,Long,Integer,Float,Object[#434],Object[#1496],Object[#1498],Double,Double,Double,Integer},{})
    append_frame(@269,Integer)
    same_frame(@276)
    same_frame(@287)
    same_frame(@327)
    same_frame(@346)
    same_frame(@365)
    same_frame(@400)
    same_locals_1_stack_item_frame(@425,Object[#646])
    full_frame(@426,{Object[#2],Float,Long,Integer,Float,Object[#434],Object[#1496],Object[#1498],Double,Double,Double,Integer,Integer},{Object[#646],Integer})
    same_frame_extended(@491)
    same_frame(@524)
    same_frame(@541)
    same_frame(@547)
    same_frame(@578)
    append_frame(@616,Top,Top,Object[#1583])
    same_frame(@654)
    same_frame(@677)
    same_frame(@725)
    same_frame(@728)
    same_frame(@737)
    same_frame(@756)
    same_frame_extended(@828)
    same_frame(@848)
    append_frame(@928,Top,Top,Integer)
    same_frame(@960)
    append_frame(@1113,Object[#753])
    same_frame(@1142)
    chop_frame(@1148,1)
    append_frame(@1298,Object[#753])
    same_frame(@1327)
    chop_frame(@1333,1)
    same_frame_extended(@1412)
    same_frame(@1450)
    same_frame(@1466)
    same_frame(@1472)
    same_frame(@1503)
    same_frame(@1516)
    same_frame(@1534)
    same_frame_extended(@1636)
    same_frame(@1682)
    same_frame(@1689)
    same_frame(@1697)
    same_frame(@1717)
    same_frame(@1725)
    same_frame(@1742)
    same_frame(@1757)
    same_frame(@1778)
    same_frame(@1795)
    same_frame_extended(@1878)
    same_frame_extended(@1948)
    same_frame(@1988)
    append_frame(@2073,Top,Integer)
    same_frame(@2095)
    same_frame(@2102)
    same_frame(@2110)
    full_frame(@2134,{Object[#2],Float,Long,Integer,Float,Object[#434],Object[#1496],Object[#1498],Double,Double,Double,Integer},{})
    chop_frame(@2140,1)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 138839392 bytes (132 MB) / 429473792 bytes (409 MB) up to 1216348160 bytes (1160 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1200M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 Optifine OptiFine_1.7.10_HD_U_E7 99 mods loaded, 99 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCH	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCH	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCH	gasesFrameworkCore{1.2.4} [Gases Framework Core] (minecraft.jar) 
	UCH	gasesCore{1.6.7} [Glenn's Gases Core] (minecraft.jar) 
	UCH	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCH	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCH	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	simpleores{1.4.3} [SimpleOres 2] ([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) 
	UCH	aestheticsplugin{1.0.0} [SimpleOres 2 Aesthetics Plugin] ([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) 
	UCH	fusionplugin{1.4.3} [SimpleOres 2 Fusion Plugin] ([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) 
	UCH	netherrocks{1.1.2} [SimpleOres 2 Netherrocks Plugin] ([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) 
	UCH	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCH	ArmorStatusHUD{1.27} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.27.jar) 
	UCH	StatusEffectHUD{1.26} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.26.jar) 
	UCH	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCH	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCH	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft-Mod-1.7.10 (1).jar) 
	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (Biomes-O-Plenty-Mod-1.7.10.jar) 
	UCH	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCH	BNBGamingLib{2.3.2} [BNBGamingLib] (BNBGamingLib-1.7.10.jar) 
	UCH	candycraftmod{Beta 1.3} [CandyCraft] (CandyCraft-1.3.jar) 
	UCH	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCH	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-1.7.10.jar) 
	UCH	coralmod{1.7.10_dev2} [CoralReef Mod] (Coral-Reef-Mod-1.7.10-Scuba-Diving.jar) 
	UCH	nandoprops{1.7.10_dev2} [NandoProps] (Coral-Reef-Mod-1.7.10-Scuba-Diving.jar) 
	UCH	craftingpillars{1.6.0} [Crafting Pillars Mod] (CraftingPillars-1.7.x-1.6.1 (1).jar) 
	UCH	DeeperCaves{0.2.2} [DeeperCaves] (Deeper-Caves-Mod-1.7.10.jar) 
	UCH	source_code293.digitalxp{0.1.5} [DigitalXP] (DigitalXP-1.7.10-0.1.5.jar) 
	UCH	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCH	DynamicLights{1.3.5} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_mobEquipment{1.0.5} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCH	golems{1.1} [Extra Golems] (Extra-Golems[1.7.10]-1.13.jar) 
	UCH	ExtraUtilities{1.2.12} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) 
	UCH	Waila{1.5.3} [Waila] (Waila-1.5.3_1.7.10.jar) 
	UCH	meteors{2.13} [Falling Meteors] (Falling-Meteors-Mod-1.7.10.jar) 
	UCH	GalacticraftCore{3.0.12} [Galacticraft Core] (Galacticraft-Mod-1.7.10.jar) 
	UCH	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-Mod-1.7.10.jar) 
	UCH	gasesFramework{1.2.4} [Gases Framework] (Gases-Framework-Mod-1.7.10.jar) 
	UCH	gases{1.6.7} [Glenn's Gases] (Glenns-Gases-Mod-1.7.10.jar) 
	UCH	grapplemod{1.7.10-v10} [Grappling hook mod] (Grappling-Hook-Mod-1.7.10.jar) 
	UCH	GraveStone{2.17.1} [GraveStone] (GraveStone-2.17.1.jar) 
	UCH	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) 
	UCH	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) 
	UCH	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) 
	UCH	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) 
	UCH	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) 
	UCH	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) 
	UCH	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) 
	UCH	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) 
	UCH	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) 
	UCH	hammertime{Hammer Time-1.7.10-1.3.6} [Hammer Time!] (HammerTime-1.3.6 (1).jar) 
	UCH	Highlands{2.2.3} [Highlands] (Highlands-Mod-1.7.10.jar) 
	UCH	howlingmoon{1.1.1} [Howling Moon] (Howling-Moon-Mod-1.7.10.jar) 
	UCH	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCH	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCH	ThinkBigCore{1.4} [§5§m===§r §e§lThink Big Core §5§m===§r] (Think-Big-Core-1.7.10 (1).jar) 
	UCH	LOT{1.2} [§9§lLots of Things] (Lots-of-Things-Mod-1.7.10.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2 (1).jar) 
	UCH	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCH	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCH	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCH	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mine-Blade-Battlegear-2-Mod-1.7.10.jar) 
	UCH	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCH	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80 (1).jar) 
	UCH	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10.jar) 
	UCH	modernalchemy{Beta-1.1} [Modern Alchemy] (Modern-Alchemy-Mod-1.7.10.jar) 
	UCH	MoreBows2{Beta 0.2} [More Bows 2] (MoreBows-0.3BETA.jar) 
	UCH	AencEx{0.0.1} [AencEx] (MoreEnchantments-1.7.X-1.1.jar) 
	UCH	me{1.1} [More Enchantments] (MoreEnchantments-1.7.X-1.1.jar) 
	UCH	MoreFurnaces{1.3.9} [More Furnaces] (MoreFurnaces-1.3.9-MC1.7.10.jar) 
	UCH	AS_MultiMine{1.4.3} [Multi Mine] (MultiMine-1.7.10.jar) 
	UCH	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCH	newfoods2{2.2} [New Foods 2] (New-Foods-2-Mod-1.7.10.jar) 
	UCH	noshelter{2.1} [noshelter] (NoShelter-Mod-1.7.10 (1).jar) 
	UCH	PastriesPlus{1.3.0} [PastriesPlus] (Pastries-Mod-1.7.10.zip) 
	UCH	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
	UCH	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6.jar) 
	UCH	Roguelike{1.3.6} [Roguelike Dungeons] (Roguelike-Dungeons-Mod-1.7.10.jar) 
	UCH	runicdungeons{1.1.7b} [Runic Dungeons] (RunicDungeons-1.1.7b.jar) 
	UCH	elysium{1.0} [The Elysium] (The-Elysium-Mod-1.7.10.jar) 
	UCH	thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
	UCH	thebombzenapi{2.4.1} [ThebombzenAPI] (ThebombzenAPI-v2.4.1-mc1.7.2.jar) 
	UCH	daventuremod{1.1} [The Daventure Mod] (TheDaventureMod-v1.1a-1.7.10.jar) 
	UCH	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7 (1).jar) 
	UCH	UsefulFood{1.4.5} [UsefulFood] (UsefulFood-1.7.10-1.4.5.jar) 
	UCH	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) 
	UCH	wildcaves3{1.7.10} [Wild Caves 3] (Wild-Caves-Mod-1.7.10 (1).jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 4600'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.1.3-327
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Launched Version: 1.7.10-Forge10.13.4.1566-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by gabe234124213** [comment]
pls help me and thx :)

**Comment by gabe234124213** [comment]
### hi****

**Comment by IchHabeHunger54** [comment]
Forge 1.7.10 is not supported anymore, and I think this mod ain't either. I don't think you will get any support here, as 1.7.10 is an ugly version and nobody uses it anymore. If you wanna play this mod, use 1.10.2. It isn't beautiful either, but it is way easier to fix something.

**Comment by gabe234124213** [comment]
Oh ok thx but if I use that versión I dont hace mucho apache Ford mods

**Comment by Mosslii** [comment]
i hope its not too late, but the betweenlands mod causes this issue on 1.7.10 with optifine. thankfully someone made [an unofficial update for the betweenlands that fixes this.](https://github.com/HRudyPlayZ/The-Betweenlands/releases/tag/1.0.7-release)

**Comment by 737** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到，尽快会给您回复。谢谢!
