### ISSUE TITLE
Ars Magica >> Server Packet Failed to Handle! [...] Packet Type: 41

### ISSUE THREAD

**Issue by Kadaban** [Mithion/ArsMagica2#470]
Saw a NPE in the server logs about an hour after playing. Not exactly sure what we were doing but we were setting up a gate network with keystones and all. Here's the crash log part that kept repeating a couple of times:

[ForgeModLoader] Ars Magica >> Server Packet Failed to Handle!
[ForgeModLoader] Ars Magica >> Packet Type: 41
[STDERR] java.lang.NullPointerException
[STDERR]    at am2.items.ContainerKeystone.setInventoryToCombination(ContainerKeystone.java:234)
[STDERR]    at am2.network.ServerPacketHandler.handleSetKeystoneCombo(ServerPacketHandler.java:137)
[STDERR]    at am2.network.ServerPacketHandler.onPacketData(ServerPacketHandler.java:114)
[STDERR]    at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
[STDERR]    at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
[STDERR]    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
[STDERR]    at net.minecraft.network.NetServerHandler.func_72501_a(NetServerHandler.java:1130)
[STDERR]    at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
[STDERR]    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
[STDERR]    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
[STDERR]    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
[STDERR]    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
[STDERR]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
[STDERR]    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
[STDERR]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
[STDERR]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[STDERR]    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

Will try to get more info when I'm on the server again.

**Comment by QelioX** [comment]
I have the error with Keystones at 1.7.10_AM2-1.4.0.008
If i shift + right click on the any block i'll get follow error:

[01:42:05] [Server thread/WARN]: Failed to handle packet for /188.112.205.15:29206
java.lang.NullPointerException
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:946) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
[01:42:05] [Server thread/INFO]: user lost connection: Internal server error
