### ISSUE TITLE
ClassCastException crashes Server and Client

### ISSUE THREAD

**Issue by zetti68** [Mithion/ArsMagica2#504]
Hello Mithion!
First of all thank you for this mod, we like it!

We have a private server with a lot of mods. The unification function by GregTech mod is also active. May be, it is the reason for this crash:

Server and client crash sometimes, when we break a lectern with a book on it. Here is the stacktrace:

java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to am2.blocks.tileentities.TileEntityBlockLectern
    at am2.blocks.tileentities.TileEntityCraftingAltar.updateLecternInformation(TileEntityCraftingAltar.java:525)
    at am2.blocks.tileentities.TileEntityCraftingAltar.func_70316_g(TileEntityCraftingAltar.java:485)
    at net.minecraft.world.World.func_72939_s(World.java:2782)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

I saw in your file, that you call a cast to your class TileEntityBlockLectern. Please check before cast whether it is from type TileEntityBlockLectern.

Thanks in advance
Zetti68

Minecraft Server 1.6.4
Clients Forge 1.6.4 B965

**Comment by EoD** [comment]
I just wanted to mention that this can be worked around by changing the following line in ``config/railcraft/blocks.cfg`` instead of removing the whole Railcraft mod:
```
B:residual.heat=false
```

Do you think it's a good idea to include this in the AM2 FAQ, too?

**Comment by Mithion** [comment]
That's what I mean by suggesting that you disable the heat feature in Railcraft.
I've added it to the mod's FAQ.
