### ISSUE TITLE
[1.4.005] Appropriation Ticking Entity Crash

### ISSUE THREAD

**Issue by BakuMinerGuy** [Mithion/ArsMagica2#924]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 03/10/14 18:10
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
	at net.minecraft.world.World.func_147465_d(World.java:441)
	at am2.spell.components.Appropriation.restore(Appropriation.java:225)
	at am2.spell.components.Appropriation.applyEffectBlock(Appropriation.java:93)
	at am2.spell.SpellHelper.applyStageToGround(SpellHelper.java:69)
	at am2.entities.EntitySpellProjectile.HitObject(EntitySpellProjectile.java:323)
	at am2.entities.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:257)
	at net.minecraft.world.World.func_72866_a(World.java:2043)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2007)
	at net.minecraft.world.World.func_72939_s(World.java:1860)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
	at net.minecraft.world.World.func_147465_d(World.java:441)
	at am2.spell.components.Appropriation.restore(Appropriation.java:225)
	at am2.spell.components.Appropriation.applyEffectBlock(Appropriation.java:93)
	at am2.spell.SpellHelper.applyStageToGround(SpellHelper.java:69)
	at am2.entities.EntitySpellProjectile.HitObject(EntitySpellProjectile.java:323)
	at am2.entities.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:257)
	at net.minecraft.world.World.func_72866_a(World.java:2043)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2007)

-- Entity being ticked --
Details:
	Entity Type: arsmagica2.SpellProjectile (am2.entities.EntitySpellProjectile)
	Entity ID: 227735
	Entity Name: entity.arsmagica2.SpellProjectile.name
	Entity's Exact location: 972.10, 4.25, 259.24
	Entity's Block location: World: (972,4,259), Chunk: (at 12,0,3 in 60,16; contains blocks 960,0,256 to 975,255,271), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.93, -0.47, -0.34
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1860)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New Worldie
	All players: 1 total; [EntityPlayerMP['BakuMinerGuy'/51, l='New Worldie', x=965.50, y=5.99, z=261.50]]
	Chunk stats: ServerChunkCache: 303 Drop: 0
	Level seed: -410401416235355331
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (972,4,268), Chunk: (at 12,0,12 in 60,16; contains blocks 960,0,256 to 975,255,271), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 1321 game time, 1321 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 95267 (now: false), thunder time: 120121 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 207605216 bytes (197 MB) / 430600192 bytes (410 MB) up to 2608070656 bytes (2487 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2500M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:MaxPermSize=40G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.25.1208 Minecraft Forge 10.13.0.1208 17 mods loaded, 17 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.25.1208} [Forge Mod Loader] (forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.0.1208} [Minecraft Forge] (forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.3.25} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.51} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.51-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.005} [Ars Magica 2] (1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons{1.12.2.9} [NEI Addons] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.7} [Baubles] (Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.300} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.300} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.300} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['BakuMinerGuy'/51, l='New Worldie', x=965.50, y=5.99, z=261.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

To reproduce the bug:

Step 1.  Make a projectile-appropriation spell.
Step 2.  Cast the spell at any block.

Appropriating mobs is fine, and you can pick up blocks, it's just when you try to replace the block that Minecraft has a fit.

**Comment by Mithion** [comment]
This has been corrected in 1.4.0.007 (dev).
