### ISSUE TITLE
[1.7.10] Entities derived from EntityPlayer crash game upon picking up the compendium

### ISSUE THREAD

**Issue by chaoskagami** [Mithion/ArsMagica2#978]
I'm not entirely sure if there's very many mods which do this, but it can be demonstrated by using littleMaidMobs and Ars Magica2 together. Create a world in creative mode, spawn egg, give a cake, and then toss the compendium at her. Game crashes in a reproducible manner with this. I'm assuming AM is not checking whether the entity is a EntityPlayer and not a subclass, and the class cast error happens because any subclasses pass through uncaught. That said, mods probably should not derive entities from EntityPlayer, because that's supposed to be reserved for players. I'm assuming Thaumcraft4's golems may also trigger this (have not tested), as well as a few other 'golem/follower' type mods. I did not test this on a server, but I can do that, if it'd help. Error log is as follows:

---- Minecraft Crash Report ----
// Sorry :(

Time: 12/21/14 5:03 AM
Description: Ticking entity

java.lang.ClassCastException: littleMaidMobX.LMM_EntityLittleMaidAvatar cannot be cast to net.minecraft.entity.player.EntityPlayerMP
    at am2.lore.CompendiumUnlockHandler.onPlayerPickupItem(CompendiumUnlockHandler.java:46)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_52_CompendiumUnlockHandler_onPlayerPickupItem_EntityItemPickupEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:345)
    at littleMaidMobX.LMM_EntityLittleMaid.func_70636_d(LMM_EntityLittleMaid.java:1649)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at littleMaidMobX.LMM_EntityLittleMaid.func_70071_h_(LMM_EntityLittleMaid.java:1848)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at am2.lore.CompendiumUnlockHandler.onPlayerPickupItem(CompendiumUnlockHandler.java:46)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_52_CompendiumUnlockHandler_onPlayerPickupItem_EntityItemPickupEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:345)
    at littleMaidMobX.LMM_EntityLittleMaid.func_70636_d(LMM_EntityLittleMaid.java:1649)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at littleMaidMobX.LMM_EntityLittleMaid.func_70071_h_(LMM_EntityLittleMaid.java:1848)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: lmmx.LittleMaidX (littleMaidMobX.LMM_EntityLittleMaid)
    Entity ID: 8642
    Entity Name: entity.lmmx.LittleMaidX.name
    Entity's Exact location: 388.50, 70.00, -270.50
    Entity's Block location: World: (388,70,-271), Chunk: (at 4,4,1 in 24,-17; contains blocks 384,0,-272 to 399,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: Test Crash
    All players: 1 total; [EntityPlayerMP['otakutaku'/4300, l='Test Crash', x=389.48, y=69.92, z=-269.28]]
    Chunk stats: ServerChunkCache: 347 Drop: 0
    Level seed: -2780551783721013290
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (412,64,-284), Chunk: (at 12,4,4 in 25,-18; contains blocks 400,0,-288 to 415,255,-273), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 1427 game time, 1427 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 127053 (now: false), thunder time: 35252 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.14.25-mukyun1
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 227832928 bytes (217 MB) / 657829888 bytes (627 MB) up to 4268163072 bytes (4070 MB)
    JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1272 Minecraft Forge 10.13.2.1272 8 mods loaded, 8 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.10.85.1272} [Forge Mod Loader](forge-1.7.10-10.13.2.1272.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.13.2.1272} [Minecraft Forge](forge-1.7.10-10.13.2.1272.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    OldModelLoader{1.0} [OldModelLoader](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    arsmagica2{1.4.0.005} [Ars Magica 2](1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    lmmx{1.0} [lmmx](littleMaidMobX-1.7.10_0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    MMMLibX{1.7.x-srg-1} [MMMLibX](littleMaidMobX-1.7.10_0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    zabuton{1.0} [zabuton](littleMaidMobX-1.7.10_0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['otakutaku'/4300, l='Test Crash', x=389.48, y=69.92, z=-269.28]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by chaoskagami** [comment]
Just a follow-up. I'm inclined to agree with you on that. It really shouldn't be coded that way. Also, build .006 still exhibits the issue, so is it safe to assume that .007 will bundle the fix?
